#!/usr/bin/env bash
set -euo pipefail

APP_ID="byte-pet"
APP_CMD="byte-pet"
MODEL_NAME="${MODEL_NAME:-llama3.2:3b}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
BIN_HOME="${XDG_BIN_HOME:-$HOME/.local/bin}"
APPS_DIR="$DATA_HOME/applications"
INSTALL_DIR="$DATA_HOME/$APP_ID"
INSTALL_BIN="$INSTALL_DIR/$APP_CMD"
LAUNCHER="$BIN_HOME/$APP_CMD"
DESKTOP_FILE="$APPS_DIR/$APP_ID.desktop"
TMP_DIR="$(mktemp -d -t bytepet-installer-XXXXXX)"

cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

need_cmd() {
  command -v "$1" >/dev/null 2>&1
}

python_has_shared_lib() {
  local py="$1"
  "$py" - <<'PY' >/dev/null 2>&1
import sysconfig
print("ok" if int(bool(sysconfig.get_config_var("Py_ENABLE_SHARED"))) else "no")
PY
}

choose_build_python() {
  local candidates=()

  if [[ -n "${BYTE_BUILD_PYTHON:-}" ]]; then
    candidates+=("$BYTE_BUILD_PYTHON")
  fi

  candidates+=("/usr/bin/python3")

  if need_cmd python3; then
    candidates+=("$(command -v python3)")
  fi
  if need_cmd python; then
    candidates+=("$(command -v python)")
  fi

  local seen=":"
  local c
  for c in "${candidates[@]}"; do
    [[ -z "$c" ]] && continue

    if [[ "$c" != /* ]]; then
      if ! c="$(command -v "$c" 2>/dev/null)"; then
        continue
      fi
    fi

    [[ -x "$c" ]] || continue
    case "$seen" in
      *":$c:"*) continue ;;
      *) seen+="$c:" ;;
    esac

    if python_has_shared_lib "$c"; then
      echo "$c"
      return 0
    fi
  done

  return 1
}

install_system_packages() {
  if need_cmd apt-get; then
    if need_cmd sudo; then
      sudo apt-get update
      sudo apt-get install -y python3 python3-venv python3-dev python3-tk xdotool espeak-ng
    else
      apt-get update
      apt-get install -y python3 python3-venv python3-dev python3-tk xdotool espeak-ng
    fi
  elif need_cmd dnf; then
    if need_cmd sudo; then
      sudo dnf install -y python3 python3-pip python3-devel python3-tkinter xdotool espeak-ng
    else
      dnf install -y python3 python3-pip python3-devel python3-tkinter xdotool espeak-ng
    fi
  elif need_cmd pacman; then
    if need_cmd sudo; then
      sudo pacman -Sy --noconfirm python python-pip tk xdotool espeak-ng
    else
      pacman -Sy --noconfirm python python-pip tk xdotool espeak-ng
    fi
  elif need_cmd zypper; then
    if need_cmd sudo; then
      sudo zypper --non-interactive install python3 python3-pip python3-devel python3-tk xdotool espeak-ng
    else
      zypper --non-interactive install python3 python3-pip python3-devel python3-tk xdotool espeak-ng
    fi
  else
    echo "Warning: unsupported package manager. Install manually: python3 python3-venv python3-dev python3-tk xdotool espeak-ng"
  fi
}

install_headless_web_stack() {
  if need_cmd apt-get; then
    if need_cmd sudo; then
      sudo apt-get install -y xvfb x11vnc novnc python3-websockify openbox >/dev/null 2>&1 || true
    else
      apt-get install -y xvfb x11vnc novnc python3-websockify openbox >/dev/null 2>&1 || true
    fi
  elif need_cmd dnf; then
    if need_cmd sudo; then
      sudo dnf install -y xorg-x11-server-Xvfb x11vnc novnc python3-websockify openbox >/dev/null 2>&1 || true
    else
      dnf install -y xorg-x11-server-Xvfb x11vnc novnc python3-websockify openbox >/dev/null 2>&1 || true
    fi
  elif need_cmd pacman; then
    if need_cmd sudo; then
      sudo pacman -Sy --noconfirm xorg-server-xvfb x11vnc novnc websockify openbox >/dev/null 2>&1 || true
    else
      pacman -Sy --noconfirm xorg-server-xvfb x11vnc novnc websockify openbox >/dev/null 2>&1 || true
    fi
  elif need_cmd zypper; then
    if need_cmd sudo; then
      sudo zypper --non-interactive install xvfb-run x11vnc novnc python3-websockify openbox >/dev/null 2>&1 || true
    else
      zypper --non-interactive install xvfb-run x11vnc novnc python3-websockify openbox >/dev/null 2>&1 || true
    fi
  fi
}

extract_embedded_source() {
  local out_path="$1"
  local payload
  payload="$(awk '/^__BYTE_SOURCE_B64__$/ {flag=1; next} /^__BYTE_SOURCE_END__$/ {flag=0} flag {print}' "$0")"
  if [[ -z "${payload//[[:space:]]/}" ]]; then
    return 1
  fi
  printf '%s' "$payload" | tr -d '\r\n\t ' | base64 -d > "$out_path"
}

build_native_executable() {
  local source_file="$1"
  local build_python="$2"
  local venv_dir="$TMP_DIR/build-venv"
  local build_dir="$TMP_DIR/pyinstaller"

  "$build_python" -m venv "$venv_dir"
  "$venv_dir/bin/python" -m pip install --upgrade pip >/dev/null
  "$venv_dir/bin/python" -m pip install pyinstaller >/dev/null

  "$venv_dir/bin/pyinstaller" \
    --noconfirm \
    --clean \
    --onefile \
    --name "$APP_CMD" \
    --distpath "$build_dir/dist" \
    --workpath "$build_dir/work" \
    --specpath "$build_dir/spec" \
    "$source_file" >/dev/null

  echo "$build_dir/dist/$APP_CMD"
}

echo "[1/8] Installing required packages (if possible)..."
install_system_packages || true
echo "[1b/8] Installing optional headless web stack (best effort)..."
install_headless_web_stack || true

echo "[2/8] Locating a shared-library Python for PyInstaller..."
BUILD_PYTHON="$(choose_build_python || true)"
if [[ -z "$BUILD_PYTHON" ]]; then
  echo "Error: no suitable Python found for PyInstaller (shared library required)."
  echo "Hint: install distro Python and retry, e.g. /usr/bin/python3"
  echo "Optional: set BYTE_BUILD_PYTHON=/path/to/python3"
  exit 1
fi

if ! "$BUILD_PYTHON" -m venv --help >/dev/null 2>&1; then
  echo "Error: selected Python does not support venv: $BUILD_PYTHON"
  exit 1
fi

echo "Using build Python: $BUILD_PYTHON"

echo "[3/8] Preparing install directories..."
mkdir -p "$INSTALL_DIR" "$BIN_HOME" "$APPS_DIR"

echo "[4/8] Extracting embedded app payload..."
SOURCE_FILE="$TMP_DIR/byte_payload.py"
if ! extract_embedded_source "$SOURCE_FILE"; then
  echo "Error: embedded payload not found in install.sh"
  exit 1
fi

echo "[5/8] Building native Linux executable for this system..."
APP_BINARY="$(build_native_executable "$SOURCE_FILE" "$BUILD_PYTHON")"
if [[ ! -f "$APP_BINARY" ]]; then
  echo "Error: failed to build executable"
  exit 1
fi

echo "[6/8] Installing executable..."
install -m 755 "$APP_BINARY" "$INSTALL_BIN"

if [[ -f "$SCRIPT_DIR/robot_pet_config.json" && ! -f "$INSTALL_DIR/robot_pet_config.json" ]]; then
  cp "$SCRIPT_DIR/robot_pet_config.json" "$INSTALL_DIR/robot_pet_config.json"
fi

echo "[7/8] Creating launcher and desktop entry..."
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
set -euo pipefail

if [[ -z "\${DISPLAY:-}" && -z "\${WAYLAND_DISPLAY:-}" ]]; then
  if [[ "\${BYTE_HEADLESS_WEB:-1}" != "1" ]]; then
    echo "No DISPLAY/WAYLAND_DISPLAY found." >&2
    echo "Headless mode is disabled (BYTE_HEADLESS_WEB!=1)." >&2
    echo "Set BYTE_HEADLESS_WEB=1 to enable web/VNC mode." >&2
    exit 1
  fi

  for cmd in Xvfb x11vnc; do
    if ! command -v "\$cmd" >/dev/null 2>&1; then
      echo "Missing '\$cmd' for headless mode. Re-run installer or install it manually." >&2
      exit 1
    fi
  done

  export DISPLAY="\${BYTE_HEADLESS_DISPLAY:-:99}"
  export XDG_RUNTIME_DIR="\${XDG_RUNTIME_DIR:-/tmp/byte-pet-runtime-\$UID}"
  mkdir -p "\$XDG_RUNTIME_DIR"

  XVFB_SCREEN="\${BYTE_XVFB_SCREEN:-1280x800x24}"
  VNC_PORT="\${BYTE_VNC_PORT:-5901}"
  WEB_PORT="\${BYTE_WEB_PORT:-6080}"
  NOVNC_DIR="\${BYTE_NOVNC_DIR:-/usr/share/novnc}"

  Xvfb "\$DISPLAY" -screen 0 "\$XVFB_SCREEN" -ac +extension RANDR >/dev/null 2>&1 &
  XVFB_PID=\$!
  sleep 0.6

  WM_PID=""
  if command -v openbox >/dev/null 2>&1; then
    openbox >/dev/null 2>&1 &
    WM_PID=\$!
  elif command -v fluxbox >/dev/null 2>&1; then
    fluxbox >/dev/null 2>&1 &
    WM_PID=\$!
  elif command -v twm >/dev/null 2>&1; then
    twm >/dev/null 2>&1 &
    WM_PID=\$!
  fi

  x11vnc -display "\$DISPLAY" -forever -shared -nopw -localhost -rfbport "\$VNC_PORT" >/dev/null 2>&1 &
  X11VNC_PID=\$!

  NOVNC_PID=""
  if command -v novnc_proxy >/dev/null 2>&1; then
    novnc_proxy --listen "\$WEB_PORT" --vnc "127.0.0.1:\$VNC_PORT" >/dev/null 2>&1 &
    NOVNC_PID=\$!
  elif command -v websockify >/dev/null 2>&1 && [[ -d "\$NOVNC_DIR" ]]; then
    websockify --web "\$NOVNC_DIR" "\$WEB_PORT" "127.0.0.1:\$VNC_PORT" >/dev/null 2>&1 &
    NOVNC_PID=\$!
  elif command -v python3 >/dev/null 2>&1 && [[ -d "\$NOVNC_DIR" ]]; then
    python3 -m websockify --web "\$NOVNC_DIR" "\$WEB_PORT" "127.0.0.1:\$VNC_PORT" >/dev/null 2>&1 &
    NOVNC_PID=\$!
  else
    echo "Warning: noVNC/websockify not found. VNC running on localhost:\$VNC_PORT only." >&2
  fi

  cleanup_headless() {
    [[ -n "\${NOVNC_PID:-}" ]] && kill "\$NOVNC_PID" >/dev/null 2>&1 || true
    kill "\$X11VNC_PID" >/dev/null 2>&1 || true
    [[ -n "\${WM_PID:-}" ]] && kill "\$WM_PID" >/dev/null 2>&1 || true
    kill "\$XVFB_PID" >/dev/null 2>&1 || true
  }
  trap cleanup_headless EXIT INT TERM

  echo "Byte Pet headless mode is running."
  echo "Open in browser: http://localhost:\$WEB_PORT/vnc.html?autoconnect=1&resize=scale"
  echo "In Codespaces, forward port \$WEB_PORT and open that forwarded URL."
fi

exec "$INSTALL_BIN" "\$@"
EOF
chmod +x "$LAUNCHER"

cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Type=Application
Name=Byte Pet
Comment=Desktop robot pet companion
Exec=$LAUNCHER
Terminal=true
Categories=Utility;
EOF

if need_cmd update-desktop-database; then
  update-desktop-database "$APPS_DIR" >/dev/null 2>&1 || true
fi

echo "[8/8] Optional Ollama model pull..."
if [[ "${BYTE_SKIP_MODEL_PULL:-0}" == "1" ]]; then
  echo "Skipping Ollama model pull (BYTE_SKIP_MODEL_PULL=1)."
elif need_cmd ollama; then
  ollama pull "$MODEL_NAME" || echo "Warning: could not pull $MODEL_NAME"
else
  echo "Ollama not found. Install Ollama manually if chat is needed."
fi

echo
echo "Install complete."
echo "Run with: $APP_CMD"
echo "If command not found, add this to your shell rc:"
echo "export PATH=\"$BIN_HOME:\$PATH\""
echo "If build-python selection was wrong, rerun with:"
echo "BYTE_BUILD_PYTHON=/usr/bin/python3 ./install.sh"

exit 0
__BYTE_SOURCE_B64__
77u/IiIiRGVza3RvcCByb2JvdCBwZXQgdGhhdCBmb2xsb3dzIHRoZSBnbG9iYWwgbW91c2UgY3Vyc29yLgoKVGVybWluYWwgbWVudSBvcHRpb25zOgotIHRv
Z2dsZQotIG9wZW4gY3VzdG9taXplcgotIHF1aXQKIiIiCgppbXBvcnQganNvbgppbXBvcnQgbWF0aAppbXBvcnQgb3MKaW1wb3J0IHJhbmRvbQppbXBvcnQg
cXVldWUKaW1wb3J0IGh0bWwKaW1wb3J0IHN1YnByb2Nlc3MKaW1wb3J0IHRocmVhZGluZwppbXBvcnQgc3lzCmltcG9ydCB0aW1lCmltcG9ydCB1cmxsaWIu
ZXJyb3IKaW1wb3J0IHVybGxpYi5yZXF1ZXN0CmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aAppbXBvcnQgdGtpbnRlciBhcyB0awpmcm9tIHRraW50ZXIgaW1w
b3J0IGNvbG9yY2hvb3Nlcgpmcm9tIHRraW50ZXIgaW1wb3J0IHR0awoKaWYgb3MubmFtZSA9PSAibnQiOgogICAgaW1wb3J0IGN0eXBlcwogICAgZnJvbSBj
dHlwZXMgaW1wb3J0IHdpbnR5cGVzCgoKZGVmIGFwcF9kaXIoKToKICAgIGlmIGdldGF0dHIoc3lzLCAiZnJvemVuIiwgRmFsc2UpOgogICAgICAgIHJldHVy
biBQYXRoKHN5cy5leGVjdXRhYmxlKS5yZXNvbHZlKCkucGFyZW50CiAgICByZXR1cm4gUGF0aChfX2ZpbGVfXykucmVzb2x2ZSgpLnBhcmVudAoKCkNPTkZJ
R19QQVRIID0gYXBwX2RpcigpIC8gInJvYm90X3BldF9jb25maWcuanNvbiIKCk9MTEFNQV9NT0RFTCA9ICJsbGFtYTMuMjozYiIKT0xMQU1BX0NIQVRfVVJM
ID0gb3MuZW52aXJvbi5nZXQoIk9MTEFNQV9DSEFUX1VSTCIsICJodHRwOi8vMTI3LjAuMC4xOjExNDM0L2FwaS9jaGF0IikKQUlfU1lTVEVNX1BST01QVCA9
ICgKICAgICJZb3UgYXJlIEJ5dGUsIGEgY3V0ZSBkZXNrdG9wIHJvYm90IGNvbXBhbmlvbi4gIgogICAgIlJlcGx5IGxpa2UgYSBodW1hbiB1c2luZyB2ZXJ5
IHNob3J0IGFuc3dlcnMuICIKICAgICJEZWZhdWx0IHRvIG9uZSBzaG9ydCBzZW50ZW5jZSwgaWRlYWxseSAzLTEwIHdvcmRzLiAiCiAgICAiTmV2ZXIgdXNl
IGxpc3RzIHVubGVzcyBhc2tlZC4gIgogICAgIlVzZSBwbGFpbiBsYW5ndWFnZSBhbmQga2VlcCBpdCBjb25jaXNlLiIKKQoKVEhFTUVTID0gWwogICAgewog
ICAgICAgICJuYW1lIjogIlNreSIsCiAgICAgICAgImNvbG9ycyI6IHsKICAgICAgICAgICAgImJvZHkiOiAiIzhFQjdGRiIsCiAgICAgICAgICAgICJ0cmlt
IjogIiMyRDQ3NzMiLAogICAgICAgICAgICAicGFuZWwiOiAiI0RDRUJGRiIsCiAgICAgICAgICAgICJleWUiOiAiI0EzRkZFMCIsCiAgICAgICAgICAgICJw
dXBpbCI6ICIjMTEzNDI4IiwKICAgICAgICAgICAgImFjY2VudCI6ICIjRkZDQzY2IiwKICAgICAgICAgICAgInNoYWRvdyI6ICIjNkE4N0I1IiwKICAgICAg
ICB9LAogICAgfSwKICAgIHsKICAgICAgICAibmFtZSI6ICJTdGVlbCIsCiAgICAgICAgImNvbG9ycyI6IHsKICAgICAgICAgICAgImJvZHkiOiAiI0IyQzFE
MSIsCiAgICAgICAgICAgICJ0cmltIjogIiMzRDRENUMiLAogICAgICAgICAgICAicGFuZWwiOiAiI0VERjJGNyIsCiAgICAgICAgICAgICJleWUiOiAiIzdD
RjdGRiIsCiAgICAgICAgICAgICJwdXBpbCI6ICIjMDAzRTQ2IiwKICAgICAgICAgICAgImFjY2VudCI6ICIjRjdCMjY3IiwKICAgICAgICAgICAgInNoYWRv
dyI6ICIjOEM5OUE4IiwKICAgICAgICB9LAogICAgfSwKICAgIHsKICAgICAgICAibmFtZSI6ICJSb3NlIiwKICAgICAgICAiY29sb3JzIjogewogICAgICAg
ICAgICAiYm9keSI6ICIjRkZCNEEyIiwKICAgICAgICAgICAgInRyaW0iOiAiIzdBM0UzNiIsCiAgICAgICAgICAgICJwYW5lbCI6ICIjRkZFM0RBIiwKICAg
ICAgICAgICAgImV5ZSI6ICIjQTdGRjhCIiwKICAgICAgICAgICAgInB1cGlsIjogIiMxRDNDMEYiLAogICAgICAgICAgICAiYWNjZW50IjogIiNGRkQxNjYi
LAogICAgICAgICAgICAic2hhZG93IjogIiNDQzhDN0YiLAogICAgICAgIH0sCiAgICB9LAogICAgewogICAgICAgICJuYW1lIjogIk1pbnQiLAogICAgICAg
ICJjb2xvcnMiOiB7CiAgICAgICAgICAgICJib2R5IjogIiNBOEZGRDkiLAogICAgICAgICAgICAidHJpbSI6ICIjMkU2QTU2IiwKICAgICAgICAgICAgInBh
bmVsIjogIiNFM0ZGRjMiLAogICAgICAgICAgICAiZXllIjogIiM4REUwRkYiLAogICAgICAgICAgICAicHVwaWwiOiAiIzEyM0E0QiIsCiAgICAgICAgICAg
ICJhY2NlbnQiOiAiI0ZGQjcwMyIsCiAgICAgICAgICAgICJzaGFkb3ciOiAiIzdCQzdBOCIsCiAgICAgICAgfSwKICAgIH0sCl0KCkJBU0VfVyA9IDE3MApC
QVNFX0ggPSAxNjAKCgpkZWYgY2xhbXAodmFsdWUsIGxvLCBoaSk6CiAgICByZXR1cm4gbWF4KGxvLCBtaW4odmFsdWUsIGhpKSkKCgpkZWYgZGVmYXVsdF9j
b25maWcoKToKICAgIHJldHVybiB7CiAgICAgICAgInRoZW1lX2luZGV4IjogMCwKICAgICAgICAiY29sb3JzIjogZGljdChUSEVNRVNbMF1bImNvbG9ycyJd
KSwKICAgICAgICAic2NhbGUiOiAwLjU4LAogICAgICAgICJtYXhfc3BlZWQiOiA0MjAuMCwKICAgICAgICAiZm9sbG93X29mZnNldF94IjogMCwKICAgICAg
ICAiZm9sbG93X29mZnNldF95IjogMjQsCiAgICAgICAgInN0b3BfcmFkaXVzIjogMTUuMCwKICAgICAgICAiYWNjZWxlcmF0aW9uIjogOS4wLAogICAgICAg
ICJkYW1waW5nIjogOC4wLAogICAgICAgICJpZGxlX2JvYl9hbXAiOiAxLjAsCiAgICAgICAgIndhbGtfYm9iX2FtcCI6IDEuNywKICAgICAgICAiaGVhZF9i
b2JfYW1wIjogMi4wLAogICAgICAgICJsZWdfbGlmdF9hbXAiOiA3LjAsCiAgICAgICAgImFybV9zd2luZ19hbXAiOiA4LjAsCiAgICAgICAgImV5ZV9zY2Fs
ZSI6IDEuMCwKICAgICAgICAicHVwaWxfc2NhbGUiOiAxLjAsCiAgICAgICAgImJsaW5rX21pbiI6IDEuNSwKICAgICAgICAiYmxpbmtfbWF4IjogMy44LAog
ICAgICAgICJhbnRlbm5hX21vZGUiOiAwLAogICAgICAgICJvcGFjaXR5IjogMS4wLAogICAgICAgICJ0b3Btb3N0IjogVHJ1ZSwKICAgICAgICAic2hvd19z
aGFkb3ciOiBUcnVlLAogICAgICAgICJzcGVha19yZXBsaWVzIjogVHJ1ZSwKICAgICAgICAidm9pY2VfcmF0ZSI6IDEsCiAgICB9CgoKZGVmIHNhbml0aXpl
X2NvbmZpZyhjZmcpOgogICAgZml4ZWQgPSBkZWZhdWx0X2NvbmZpZygpCiAgICBmaXhlZC51cGRhdGUoe2s6IHYgZm9yIGssIHYgaW4gY2ZnLml0ZW1zKCkg
aWYgayBpbiBmaXhlZH0pCgogICAgZml4ZWRbInRoZW1lX2luZGV4Il0gPSBpbnQoY2xhbXAoaW50KGZpeGVkWyJ0aGVtZV9pbmRleCJdKSwgMCwgbGVuKFRI
RU1FUykgLSAxKSkKICAgIGlmIGlzaW5zdGFuY2UoY2ZnLmdldCgiY29sb3JzIiksIGRpY3QpOgogICAgICAgIGZpeGVkWyJjb2xvcnMiXS51cGRhdGUoY2Zn
WyJjb2xvcnMiXSkKCiAgICBmaXhlZFsic2NhbGUiXSA9IGZsb2F0KGNsYW1wKGZsb2F0KGZpeGVkWyJzY2FsZSJdKSwgMC4yOCwgMi4yKSkKICAgIGZpeGVk
WyJtYXhfc3BlZWQiXSA9IGZsb2F0KGNsYW1wKGZsb2F0KGZpeGVkWyJtYXhfc3BlZWQiXSksIDEyMC4wLCAxMzAwLjApKQogICAgZml4ZWRbImZvbGxvd19v
ZmZzZXRfeCJdID0gaW50KGNsYW1wKGludChmaXhlZFsiZm9sbG93X29mZnNldF94Il0pLCAtMjUwLCAyNTApKQogICAgZml4ZWRbImZvbGxvd19vZmZzZXRf
eSJdID0gaW50KGNsYW1wKGludChmaXhlZFsiZm9sbG93X29mZnNldF95Il0pLCAtMjAwLCAyNTApKQogICAgZml4ZWRbInN0b3BfcmFkaXVzIl0gPSBmbG9h
dChjbGFtcChmbG9hdChmaXhlZFsic3RvcF9yYWRpdXMiXSksIDIuMCwgMTIwLjApKQogICAgZml4ZWRbImFjY2VsZXJhdGlvbiJdID0gZmxvYXQoY2xhbXAo
ZmxvYXQoZml4ZWRbImFjY2VsZXJhdGlvbiJdKSwgMi4wLCAyNS4wKSkKICAgIGZpeGVkWyJkYW1waW5nIl0gPSBmbG9hdChjbGFtcChmbG9hdChmaXhlZFsi
ZGFtcGluZyJdKSwgMi4wLCAyNS4wKSkKICAgIGZpeGVkWyJpZGxlX2JvYl9hbXAiXSA9IGZsb2F0KGNsYW1wKGZsb2F0KGZpeGVkWyJpZGxlX2JvYl9hbXAi
XSksIDAuMCwgNi4wKSkKICAgIGZpeGVkWyJ3YWxrX2JvYl9hbXAiXSA9IGZsb2F0KGNsYW1wKGZsb2F0KGZpeGVkWyJ3YWxrX2JvYl9hbXAiXSksIDAuMCwg
OC4wKSkKICAgIGZpeGVkWyJoZWFkX2JvYl9hbXAiXSA9IGZsb2F0KGNsYW1wKGZsb2F0KGZpeGVkWyJoZWFkX2JvYl9hbXAiXSksIDAuMCwgMTAuMCkpCiAg
ICBmaXhlZFsibGVnX2xpZnRfYW1wIl0gPSBmbG9hdChjbGFtcChmbG9hdChmaXhlZFsibGVnX2xpZnRfYW1wIl0pLCAwLjAsIDIwLjApKQogICAgZml4ZWRb
ImFybV9zd2luZ19hbXAiXSA9IGZsb2F0KGNsYW1wKGZsb2F0KGZpeGVkWyJhcm1fc3dpbmdfYW1wIl0pLCAwLjAsIDIwLjApKQogICAgZml4ZWRbImV5ZV9z
Y2FsZSJdID0gZmxvYXQoY2xhbXAoZmxvYXQoZml4ZWRbImV5ZV9zY2FsZSJdKSwgMC41LCAxLjgpKQogICAgZml4ZWRbInB1cGlsX3NjYWxlIl0gPSBmbG9h
dChjbGFtcChmbG9hdChmaXhlZFsicHVwaWxfc2NhbGUiXSksIDAuNCwgMi4yKSkKICAgIGZpeGVkWyJibGlua19taW4iXSA9IGZsb2F0KGNsYW1wKGZsb2F0
KGZpeGVkWyJibGlua19taW4iXSksIDAuMiwgOC4wKSkKICAgIGZpeGVkWyJibGlua19tYXgiXSA9IGZsb2F0KGNsYW1wKGZsb2F0KGZpeGVkWyJibGlua19t
YXgiXSksIGZpeGVkWyJibGlua19taW4iXSArIDAuMSwgMTIuMCkpCiAgICBmaXhlZFsiYW50ZW5uYV9tb2RlIl0gPSBpbnQoY2xhbXAoaW50KGZpeGVkWyJh
bnRlbm5hX21vZGUiXSksIDAsIDIpKQogICAgZml4ZWRbIm9wYWNpdHkiXSA9IGZsb2F0KGNsYW1wKGZsb2F0KGZpeGVkWyJvcGFjaXR5Il0pLCAwLjM1LCAx
LjApKQogICAgZml4ZWRbInRvcG1vc3QiXSA9IGJvb2woZml4ZWRbInRvcG1vc3QiXSkKICAgIGZpeGVkWyJzaG93X3NoYWRvdyJdID0gYm9vbChmaXhlZFsi
c2hvd19zaGFkb3ciXSkKICAgIGZpeGVkWyJzcGVha19yZXBsaWVzIl0gPSBib29sKGZpeGVkWyJzcGVha19yZXBsaWVzIl0pCiAgICBmaXhlZFsidm9pY2Vf
cmF0ZSJdID0gaW50KGNsYW1wKGludChmaXhlZFsidm9pY2VfcmF0ZSJdKSwgLTgsIDgpKQoKICAgIHJldHVybiBmaXhlZAoKCmRlZiBsb2FkX2NvbmZpZygp
OgogICAgaWYgbm90IENPTkZJR19QQVRILmV4aXN0cygpOgogICAgICAgIHJldHVybiBkZWZhdWx0X2NvbmZpZygpCiAgICB0cnk6CiAgICAgICAgbG9hZGVk
ID0ganNvbi5sb2FkcyhDT05GSUdfUEFUSC5yZWFkX3RleHQoZW5jb2Rpbmc9InV0Zi04IikpCiAgICAgICAgcmV0dXJuIHNhbml0aXplX2NvbmZpZyhsb2Fk
ZWQpCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgIHJldHVybiBkZWZhdWx0X2NvbmZpZygpCgoKZGVmIHNhdmVfY29uZmlnKGNmZyk6CiAgICB0cnk6
CiAgICAgICAgQ09ORklHX1BBVEgud3JpdGVfdGV4dChqc29uLmR1bXBzKHNhbml0aXplX2NvbmZpZyhjZmcpLCBpbmRlbnQ9MiksIGVuY29kaW5nPSJ1dGYt
OCIpCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgIHBhc3MKCgppZiBvcy5uYW1lID09ICJudCI6CiAgICBjbGFzcyBNU0coY3R5cGVzLlN0cnVjdHVy
ZSk6CiAgICAgICAgX2ZpZWxkc18gPSBbCiAgICAgICAgICAgICgiaHduZCIsIHdpbnR5cGVzLkhXTkQpLAogICAgICAgICAgICAoIm1lc3NhZ2UiLCB3aW50
eXBlcy5VSU5UKSwKICAgICAgICAgICAgKCJ3UGFyYW0iLCB3aW50eXBlcy5XUEFSQU0pLAogICAgICAgICAgICAoImxQYXJhbSIsIHdpbnR5cGVzLkxQQVJB
TSksCiAgICAgICAgICAgICgidGltZSIsIHdpbnR5cGVzLkRXT1JEKSwKICAgICAgICAgICAgKCJwdCIsIHdpbnR5cGVzLlBPSU5UKSwKICAgICAgICAgICAg
KCJsUHJpdmF0ZSIsIHdpbnR5cGVzLkRXT1JEKSwKICAgICAgICBdCgoKY2xhc3MgR2xvYmFsSG90a2V5TWFuYWdlcjoKICAgIEhPVEtFWV9NT0RTID0gMAog
ICAgV01fSE9US0VZID0gMHgwMzEyCiAgICBQTV9SRU1PVkUgPSAweDAwMDEKICAgIEhPVEtFWV9UT0dHTEVfSUQgPSAxCiAgICBIT1RLRVlfUVVJVF9JRCA9
IDIKICAgIEhPVEtFWV9TRVRUSU5HU19JRCA9IDMKICAgIFZLX0Y2ID0gMHg3NQogICAgVktfRjcgPSAweDc2CiAgICBWS19GOCA9IDB4NzcKCiAgICBkZWYg
X19pbml0X18oc2VsZiwgb25fdG9nZ2xlLCBvbl9xdWl0LCBvbl9zZXR0aW5ncyk6CiAgICAgICAgc2VsZi5vbl90b2dnbGUgPSBvbl90b2dnbGUKICAgICAg
ICBzZWxmLm9uX3F1aXQgPSBvbl9xdWl0CiAgICAgICAgc2VsZi5vbl9zZXR0aW5ncyA9IG9uX3NldHRpbmdzCiAgICAgICAgc2VsZi5hY3RpdmUgPSBGYWxz
ZQogICAgICAgIHNlbGYudXNlcjMyID0gTm9uZQogICAgICAgIHNlbGYuaGFuZGxlcnMgPSB7CiAgICAgICAgICAgIHNlbGYuSE9US0VZX1RPR0dMRV9JRDog
c2VsZi5vbl90b2dnbGUsCiAgICAgICAgICAgIHNlbGYuSE9US0VZX1FVSVRfSUQ6IHNlbGYub25fcXVpdCwKICAgICAgICAgICAgc2VsZi5IT1RLRVlfU0VU
VElOR1NfSUQ6IHNlbGYub25fc2V0dGluZ3MsCiAgICAgICAgfQogICAgICAgIHNlbGYucmVnaXN0ZXJlZF9pZHMgPSBzZXQoKQoKICAgICAgICBpZiBvcy5u
YW1lICE9ICJudCI6CiAgICAgICAgICAgIHJldHVybgoKICAgICAgICB0cnk6CiAgICAgICAgICAgIHNlbGYudXNlcjMyID0gY3R5cGVzLndpbmRsbC51c2Vy
MzIKICAgICAgICAgICAgbW9kcyA9IHNlbGYuSE9US0VZX01PRFMKICAgICAgICAgICAgd2FudGVkID0gKAogICAgICAgICAgICAgICAgKHNlbGYuSE9US0VZ
X1RPR0dMRV9JRCwgc2VsZi5WS19GNiksCiAgICAgICAgICAgICAgICAoc2VsZi5IT1RLRVlfU0VUVElOR1NfSUQsIHNlbGYuVktfRjcpLAogICAgICAgICAg
ICAgICAgKHNlbGYuSE9US0VZX1FVSVRfSUQsIHNlbGYuVktfRjgpLAogICAgICAgICAgICApCiAgICAgICAgICAgIGZvciBob3RrZXlfaWQsIHZrIGluIHdh
bnRlZDoKICAgICAgICAgICAgICAgIG9rID0gc2VsZi51c2VyMzIuUmVnaXN0ZXJIb3RLZXkoTm9uZSwgaG90a2V5X2lkLCBtb2RzLCB2aykKICAgICAgICAg
ICAgICAgIGlmIG9rOgogICAgICAgICAgICAgICAgICAgIHNlbGYucmVnaXN0ZXJlZF9pZHMuYWRkKGhvdGtleV9pZCkKICAgICAgICAgICAgc2VsZi5hY3Rp
dmUgPSBib29sKHNlbGYucmVnaXN0ZXJlZF9pZHMpCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgc2VsZi5hY3RpdmUgPSBGYWxzZQoK
ICAgIGRlZiBwb2xsKHNlbGYpOgogICAgICAgIGlmIG5vdCBzZWxmLmFjdGl2ZSBvciBzZWxmLnVzZXIzMiBpcyBOb25lOgogICAgICAgICAgICByZXR1cm4K
CiAgICAgICAgbXNnID0gTVNHKCkKICAgICAgICB3aGlsZSBzZWxmLnVzZXIzMi5QZWVrTWVzc2FnZVcoCiAgICAgICAgICAgIGN0eXBlcy5ieXJlZihtc2cp
LAogICAgICAgICAgICBOb25lLAogICAgICAgICAgICBzZWxmLldNX0hPVEtFWSwKICAgICAgICAgICAgc2VsZi5XTV9IT1RLRVksCiAgICAgICAgICAgIHNl
bGYuUE1fUkVNT1ZFLAogICAgICAgICk6CiAgICAgICAgICAgIGhvdGtleV9pZCA9IGludChtc2cud1BhcmFtKQogICAgICAgICAgICBoYW5kbGVyID0gc2Vs
Zi5oYW5kbGVycy5nZXQoaG90a2V5X2lkKQogICAgICAgICAgICBpZiBoYW5kbGVyIGlzIG5vdCBOb25lOgogICAgICAgICAgICAgICAgaGFuZGxlcigpCgog
ICAgZGVmIGNsb3NlKHNlbGYpOgogICAgICAgIGlmIG5vdCBzZWxmLmFjdGl2ZSBvciBzZWxmLnVzZXIzMiBpcyBOb25lOgogICAgICAgICAgICByZXR1cm4K
ICAgICAgICB0cnk6CiAgICAgICAgICAgIGZvciBob3RrZXlfaWQgaW4gdHVwbGUoc2VsZi5yZWdpc3RlcmVkX2lkcyk6CiAgICAgICAgICAgICAgICBzZWxm
LnVzZXIzMi5VbnJlZ2lzdGVySG90S2V5KE5vbmUsIGhvdGtleV9pZCkKICAgICAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgICAgICBwYXNzCiAgICAg
ICAgc2VsZi5yZWdpc3RlcmVkX2lkcy5jbGVhcigpCiAgICAgICAgc2VsZi5hY3RpdmUgPSBGYWxzZQoKCmNsYXNzIFJvYm90UGV0QXBwOgogICAgZGVmIF9f
aW5pdF9fKHNlbGYpOgogICAgICAgIHNlbGYucm9vdCA9IHRrLlRrKCkKICAgICAgICBzZWxmLnJvb3QudGl0bGUoIlJvYm90IFBldCIpCiAgICAgICAgc2Vs
Zi5yb290Lm92ZXJyaWRlcmVkaXJlY3QoVHJ1ZSkKCiAgICAgICAgc2VsZi5iZ19rZXkgPSAiIzAwZmYwMCIKICAgICAgICBzZWxmLnJvb3QuY29uZmlndXJl
KGJnPXNlbGYuYmdfa2V5KQogICAgICAgIHRyeToKICAgICAgICAgICAgc2VsZi5yb290LndtX2F0dHJpYnV0ZXMoIi10cmFuc3BhcmVudGNvbG9yIiwgc2Vs
Zi5iZ19rZXkpCiAgICAgICAgZXhjZXB0IHRrLlRjbEVycm9yOgogICAgICAgICAgICBwYXNzCgogICAgICAgIHNlbGYuY2FudmFzID0gdGsuQ2FudmFzKHNl
bGYucm9vdCwgYmc9c2VsZi5iZ19rZXksIGhpZ2hsaWdodHRoaWNrbmVzcz0wLCBiZD0wKQogICAgICAgIHNlbGYuY2FudmFzLnBhY2soZmlsbD0iYm90aCIs
IGV4cGFuZD1UcnVlKQoKICAgICAgICBzZWxmLmNmZyA9IGxvYWRfY29uZmlnKCkKICAgICAgICBzZWxmLnZpc2libGUgPSBUcnVlCiAgICAgICAgc2VsZi5w
YXVzZWQgPSBGYWxzZQoKICAgICAgICBzZWxmLnggPSBzZWxmLnJvb3Qud2luZm9fc2NyZWVud2lkdGgoKSAqIDAuNDUKICAgICAgICBzZWxmLnkgPSBzZWxm
LnJvb3Qud2luZm9fc2NyZWVuaGVpZ2h0KCkgKiAwLjQ1CiAgICAgICAgc2VsZi52eCA9IDAuMAogICAgICAgIHNlbGYudnkgPSAwLjAKICAgICAgICBzZWxm
LndhbGtfcGhhc2UgPSAwLjAKICAgICAgICBzZWxmLmlkbGVfcGhhc2UgPSAwLjAKICAgICAgICBzZWxmLmZhY2luZyA9IDEKICAgICAgICBzZWxmLnR1cm4g
PSAwLjAKICAgICAgICBzZWxmLmxhc3RfdGljayA9IHRpbWUucGVyZl9jb3VudGVyKCkKCiAgICAgICAgc2VsZi5kcmFnZ2luZyA9IEZhbHNlCiAgICAgICAg
c2VsZi5kcmFnX2R4ID0gMC4wCiAgICAgICAgc2VsZi5kcmFnX2R5ID0gMC4wCgogICAgICAgIHNlbGYubmV4dF9ibGluayA9IDAuMAogICAgICAgIHNlbGYu
YmxpbmtfZW5kID0gMC4wCiAgICAgICAgc2VsZi5fc2NoZWR1bGVfbmV4dF9ibGluayhzZWxmLmxhc3RfdGljaykKCiAgICAgICAgc2VsZi5zZXR0aW5nc193
aW5kb3cgPSBOb25lCiAgICAgICAgc2VsZi5zZXR0aW5nc192YXJzID0ge30KICAgICAgICBzZWxmLmNvbG9yX3N3YXRjaGVzID0ge30KICAgICAgICBzZWxm
LmNoYXRfd2lkZ2V0cyA9IHt9CiAgICAgICAgc2VsZi5jaGF0X2hpc3RvcnkgPSBbXQogICAgICAgIHNlbGYuY2hhdF9idXN5ID0gRmFsc2UKICAgICAgICBz
ZWxmLmNoYXRfcXVldWUgPSBxdWV1ZS5RdWV1ZSgpCiAgICAgICAgc2VsZi5jaGF0X3N0cmVhbV90ZXh0ID0gIiIKICAgICAgICBzZWxmLmNoYXRfc3RyZWFt
X2luX3dpZGdldCA9IEZhbHNlCiAgICAgICAgc2VsZi5jb21tYW5kX3F1ZXVlID0gcXVldWUuUXVldWUoKQogICAgICAgIHNlbGYub2xsYW1hX21vZGVsX3Jl
YWR5ID0gRmFsc2UKICAgICAgICBzZWxmLm9sbGFtYV9tb2RlbF9sb2NrID0gdGhyZWFkaW5nLkxvY2soKQogICAgICAgIHNlbGYudm9pY2VfcXVldWUgPSBx
dWV1ZS5RdWV1ZSgpCiAgICAgICAgc2VsZi52b2ljZV9zdG9wID0gdGhyZWFkaW5nLkV2ZW50KCkKICAgICAgICBzZWxmLnZvaWNlX3RocmVhZCA9IHRocmVh
ZGluZy5UaHJlYWQodGFyZ2V0PXNlbGYuX3ZvaWNlX3dvcmtlciwgZGFlbW9uPVRydWUpCiAgICAgICAgc2VsZi52b2ljZV90aHJlYWQuc3RhcnQoKQogICAg
ICAgIHNlbGYubWVudV9zdG9wID0gdGhyZWFkaW5nLkV2ZW50KCkKICAgICAgICBzZWxmLm1lbnVfdGhyZWFkID0gTm9uZQoKICAgICAgICBzZWxmLl9hcHBs
eV9ydW50aW1lX29wdGlvbnMoKQogICAgICAgIHNlbGYuX3Jlc2l6ZV93aW5kb3coKQoKICAgICAgICBzZWxmLnJvb3QuYmluZCgiPEJ1dHRvblByZXNzLTE+
Iiwgc2VsZi5fc3RhcnRfZHJhZykKICAgICAgICBzZWxmLnJvb3QuYmluZCgiPEIxLU1vdGlvbj4iLCBzZWxmLl9kcmFnX21vdGlvbikKICAgICAgICBzZWxm
LnJvb3QuYmluZCgiPEJ1dHRvblJlbGVhc2UtMT4iLCBzZWxmLl9lbmRfZHJhZykKICAgICAgICBzZWxmLnJvb3QuYmluZCgiPEJ1dHRvbi0zPiIsIHNlbGYu
X29wZW5fc2V0dGluZ3MpCiAgICAgICAgc2VsZi5yb290LmJpbmQoIjxEb3VibGUtQnV0dG9uLTE+Iiwgc2VsZi5fdG9nZ2xlX3BhdXNlKQoKICAgICAgICBz
ZWxmLnJvb3QuZm9jdXNfZm9yY2UoKQogICAgICAgIHNlbGYuX3N0YXJ0X3Rlcm1pbmFsX21lbnUoKQogICAgICAgIHNlbGYucm9vdC5hZnRlcigwLCBzZWxm
Ll90aWNrKQoKICAgIGRlZiBydW4oc2VsZik6CiAgICAgICAgc2VsZi5yb290Lm1haW5sb29wKCkKCiAgICBkZWYgX2FwcGx5X3J1bnRpbWVfb3B0aW9ucyhz
ZWxmKToKICAgICAgICBzZWxmLmNmZyA9IHNhbml0aXplX2NvbmZpZyhzZWxmLmNmZykKICAgICAgICBzZWxmLnJvb3QuYXR0cmlidXRlcygiLXRvcG1vc3Qi
LCBib29sKHNlbGYuY2ZnWyJ0b3Btb3N0Il0pKQogICAgICAgIHRyeToKICAgICAgICAgICAgc2VsZi5yb290LmF0dHJpYnV0ZXMoIi1hbHBoYSIsIGZsb2F0
KHNlbGYuY2ZnWyJvcGFjaXR5Il0pKQogICAgICAgIGV4Y2VwdCB0ay5UY2xFcnJvcjoKICAgICAgICAgICAgcGFzcwoKICAgIGRlZiBfc2F2ZV9jb25maWco
c2VsZik6CiAgICAgICAgc2F2ZV9jb25maWcoc2VsZi5jZmcpCgogICAgZGVmIF9wZXRfc2l6ZShzZWxmKToKICAgICAgICB3ID0gaW50KEJBU0VfVyAqIGZs
b2F0KHNlbGYuY2ZnWyJzY2FsZSJdKSkKICAgICAgICBoID0gaW50KEJBU0VfSCAqIGZsb2F0KHNlbGYuY2ZnWyJzY2FsZSJdKSkKICAgICAgICByZXR1cm4g
bWF4KDUyLCB3KSwgbWF4KDQ4LCBoKQoKICAgIGRlZiBfcmVzaXplX3dpbmRvdyhzZWxmKToKICAgICAgICB3LCBoID0gc2VsZi5fcGV0X3NpemUoKQogICAg
ICAgIHNjcmVlbl93ID0gc2VsZi5yb290LndpbmZvX3NjcmVlbndpZHRoKCkKICAgICAgICBzY3JlZW5faCA9IHNlbGYucm9vdC53aW5mb19zY3JlZW5oZWln
aHQoKQogICAgICAgIHNlbGYueCA9IGNsYW1wKHNlbGYueCwgMCwgbWF4KDAsIHNjcmVlbl93IC0gdykpCiAgICAgICAgc2VsZi55ID0gY2xhbXAoc2VsZi55
LCAwLCBtYXgoMCwgc2NyZWVuX2ggLSBoKSkKICAgICAgICBzZWxmLnJvb3QuZ2VvbWV0cnkoZiJ7d314e2h9K3tpbnQoc2VsZi54KX0re2ludChzZWxmLnkp
fSIpCiAgICAgICAgc2VsZi5jYW52YXMuY29uZmlnKHdpZHRoPXcsIGhlaWdodD1oKQoKICAgIGRlZiBfcG9pbnRlcl94eShzZWxmKToKICAgICAgICB0cnk6
CiAgICAgICAgICAgIHJldHVybiBzZWxmLnJvb3Qud2luZm9fcG9pbnRlcngoKSwgc2VsZi5yb290LndpbmZvX3BvaW50ZXJ5KCkKICAgICAgICBleGNlcHQg
dGsuVGNsRXJyb3I6CiAgICAgICAgICAgIHJldHVybiBOb25lLCBOb25lCgogICAgZGVmIF9zY2hlZHVsZV9uZXh0X2JsaW5rKHNlbGYsIG5vdyk6CiAgICAg
ICAgYmxpbmtfbWluID0gZmxvYXQoc2VsZi5jZmdbImJsaW5rX21pbiJdKQogICAgICAgIGJsaW5rX21heCA9IGZsb2F0KHNlbGYuY2ZnWyJibGlua19tYXgi
XSkKICAgICAgICBzZWxmLm5leHRfYmxpbmsgPSBub3cgKyByYW5kb20udW5pZm9ybShibGlua19taW4sIGJsaW5rX21heCkKCiAgICBkZWYgX3VwZGF0ZV9i
bGluayhzZWxmLCBub3cpOgogICAgICAgIGlmIG5vdyA+PSBzZWxmLm5leHRfYmxpbms6CiAgICAgICAgICAgIHNlbGYuYmxpbmtfZW5kID0gbm93ICsgcmFu
ZG9tLnVuaWZvcm0oMC4wNiwgMC4xMikKICAgICAgICAgICAgc2VsZi5fc2NoZWR1bGVfbmV4dF9ibGluayhub3cpCgogICAgZGVmIF9zdGFydF9kcmFnKHNl
bGYsIGV2ZW50KToKICAgICAgICBzZWxmLmRyYWdnaW5nID0gVHJ1ZQogICAgICAgIHNlbGYuZHJhZ19keCA9IGV2ZW50LngKICAgICAgICBzZWxmLmRyYWdf
ZHkgPSBldmVudC55CiAgICAgICAgc2VsZi52eCA9IDAuMAogICAgICAgIHNlbGYudnkgPSAwLjAKCiAgICBkZWYgX2RyYWdfbW90aW9uKHNlbGYsIF9ldmVu
dCk6CiAgICAgICAgaWYgbm90IHNlbGYuZHJhZ2dpbmc6CiAgICAgICAgICAgIHJldHVybgogICAgICAgIHBvaW50ZXJfeCwgcG9pbnRlcl95ID0gc2VsZi5f
cG9pbnRlcl94eSgpCiAgICAgICAgaWYgcG9pbnRlcl94IGlzIE5vbmU6CiAgICAgICAgICAgIHJldHVybgogICAgICAgIHNlbGYueCA9IHBvaW50ZXJfeCAt
IHNlbGYuZHJhZ19keAogICAgICAgIHNlbGYueSA9IHBvaW50ZXJfeSAtIHNlbGYuZHJhZ19keQogICAgICAgIHNlbGYuX3Jlc2l6ZV93aW5kb3coKQoKICAg
IGRlZiBfZW5kX2RyYWcoc2VsZiwgX2V2ZW50KToKICAgICAgICBzZWxmLmRyYWdnaW5nID0gRmFsc2UKCiAgICBkZWYgX3RvZ2dsZV9wYXVzZShzZWxmLCBf
ZXZlbnQ9Tm9uZSk6CiAgICAgICAgc2VsZi5wYXVzZWQgPSBub3Qgc2VsZi5wYXVzZWQKCiAgICBkZWYgX3RvZ2dsZV92aXNpYmlsaXR5KHNlbGYsIF9ldmVu
dD1Ob25lKToKICAgICAgICBzZWxmLnZpc2libGUgPSBub3Qgc2VsZi52aXNpYmxlCiAgICAgICAgaWYgc2VsZi52aXNpYmxlOgogICAgICAgICAgICBzZWxm
LnJvb3QuZGVpY29uaWZ5KCkKICAgICAgICAgICAgc2VsZi5yb290LmF0dHJpYnV0ZXMoIi10b3Btb3N0IiwgYm9vbChzZWxmLmNmZ1sidG9wbW9zdCJdKSkK
ICAgICAgICAgICAgc2VsZi5yb290LmxpZnQoKQogICAgICAgIGVsc2U6CiAgICAgICAgICAgIHNlbGYucm9vdC53aXRoZHJhdygpCgogICAgZGVmIF9xdWl0
KHNlbGYsIF9ldmVudD1Ob25lKToKICAgICAgICBzZWxmLl9zYXZlX2NvbmZpZygpCiAgICAgICAgc2VsZi5tZW51X3N0b3Auc2V0KCkKICAgICAgICBzZWxm
LnZvaWNlX3N0b3Auc2V0KCkKICAgICAgICBzZWxmLnZvaWNlX3F1ZXVlLnB1dChOb25lKQogICAgICAgIHRyeToKICAgICAgICAgICAgc2VsZi5yb290LmRl
c3Ryb3koKQogICAgICAgIGV4Y2VwdCB0ay5UY2xFcnJvcjoKICAgICAgICAgICAgcGFzcwoKICAgIGRlZiBfc3RhcnRfdGVybWluYWxfbWVudShzZWxmKToK
ICAgICAgICBpZiBzZWxmLm1lbnVfdGhyZWFkIGlzIG5vdCBOb25lOgogICAgICAgICAgICByZXR1cm4KICAgICAgICBpZiBub3Qgc3lzLnN0ZGluIG9yIG5v
dCBzeXMuc3RkaW4uaXNhdHR5KCk6CiAgICAgICAgICAgIHJldHVybgogICAgICAgIHNlbGYubWVudV90aHJlYWQgPSB0aHJlYWRpbmcuVGhyZWFkKHRhcmdl
dD1zZWxmLl90ZXJtaW5hbF9tZW51X2xvb3AsIGRhZW1vbj1UcnVlKQogICAgICAgIHNlbGYubWVudV90aHJlYWQuc3RhcnQoKQoKICAgIGRlZiBfdGVybWlu
YWxfbWVudV9sb29wKHNlbGYpOgogICAgICAgIHdoaWxlIG5vdCBzZWxmLm1lbnVfc3RvcC5pc19zZXQoKToKICAgICAgICAgICAgcHJpbnQoIlxuPT09IFJv
Ym90IFBldCBNZW51ID09PSIpCiAgICAgICAgICAgIHByaW50KCIxKSBUb2dnbGUgcGV0IikKICAgICAgICAgICAgcHJpbnQoIjIpIE9wZW4gY3VzdG9taXpl
ciIpCiAgICAgICAgICAgIHByaW50KCIzKSBRdWl0IikKICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgY2hvaWNlID0gaW5wdXQoIkNob29zZSBb
MS0zXTogIikuc3RyaXAoKS5sb3dlcigpCiAgICAgICAgICAgIGV4Y2VwdCBFT0ZFcnJvcjoKICAgICAgICAgICAgICAgIHJldHVybgogICAgICAgICAgICBl
eGNlcHQgRXhjZXB0aW9uOgogICAgICAgICAgICAgICAgY29udGludWUKCiAgICAgICAgICAgIGlmIHNlbGYubWVudV9zdG9wLmlzX3NldCgpOgogICAgICAg
ICAgICAgICAgcmV0dXJuCgogICAgICAgICAgICBtYXBwaW5nID0gewogICAgICAgICAgICAgICAgIjEiOiAidG9nZ2xlIiwKICAgICAgICAgICAgICAgICJ0
b2dnbGUiOiAidG9nZ2xlIiwKICAgICAgICAgICAgICAgICJ0IjogInRvZ2dsZSIsCiAgICAgICAgICAgICAgICAiMiI6ICJvcGVuIiwKICAgICAgICAgICAg
ICAgICJvcGVuIjogIm9wZW4iLAogICAgICAgICAgICAgICAgIm9wZW4gY3VzdG9taXplciI6ICJvcGVuIiwKICAgICAgICAgICAgICAgICJjdXN0b21pemVy
IjogIm9wZW4iLAogICAgICAgICAgICAgICAgImMiOiAib3BlbiIsCiAgICAgICAgICAgICAgICAiMyI6ICJxdWl0IiwKICAgICAgICAgICAgICAgICJxdWl0
IjogInF1aXQiLAogICAgICAgICAgICAgICAgInEiOiAicXVpdCIsCiAgICAgICAgICAgICAgICAiZXhpdCI6ICJxdWl0IiwKICAgICAgICAgICAgfQogICAg
ICAgICAgICBjb21tYW5kID0gbWFwcGluZy5nZXQoY2hvaWNlKQogICAgICAgICAgICBpZiBjb21tYW5kIGlzIE5vbmU6CiAgICAgICAgICAgICAgICBwcmlu
dCgiSW52YWxpZCBvcHRpb24uIEVudGVyIDEsIDIsIG9yIDMuIikKICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIHNlbGYuY29tbWFuZF9x
dWV1ZS5wdXQoKGNvbW1hbmQsIE5vbmUpKQogICAgICAgICAgICBpZiBjb21tYW5kID09ICJxdWl0IjoKICAgICAgICAgICAgICAgIHJldHVybgoKICAgIGRl
ZiBfdm9pY2Vfd29ya2VyKHNlbGYpOgogICAgICAgIHdoaWxlIG5vdCBzZWxmLnZvaWNlX3N0b3AuaXNfc2V0KCk6CiAgICAgICAgICAgIHRyeToKICAgICAg
ICAgICAgICAgIHRleHQgPSBzZWxmLnZvaWNlX3F1ZXVlLmdldCh0aW1lb3V0PTAuMikKICAgICAgICAgICAgZXhjZXB0IHF1ZXVlLkVtcHR5OgogICAgICAg
ICAgICAgICAgY29udGludWUKCiAgICAgICAgICAgIGlmIHRleHQgaXMgTm9uZToKICAgICAgICAgICAgICAgIHJldHVybgoKICAgICAgICAgICAgY2xlYW5l
ZCA9ICIgIi5qb2luKHN0cih0ZXh0KS5zcGxpdCgpKQogICAgICAgICAgICBpZiBub3QgY2xlYW5lZDoKICAgICAgICAgICAgICAgIGNvbnRpbnVlCgogICAg
ICAgICAgICBpZiBvcy5uYW1lID09ICJudCI6CiAgICAgICAgICAgICAgICBzZWxmLl9zcGVha193aW5kb3dzKGNsZWFuZWQpCiAgICAgICAgICAgIGVsc2U6
CiAgICAgICAgICAgICAgICBwYXNzCgogICAgZGVmIF9yb2JvdGljaXplX3ZvaWNlX3RleHQoc2VsZiwgdGV4dCk6CiAgICAgICAgYmFzZSA9ICIgIi5qb2lu
KHN0cih0ZXh0KS5zdHJpcCgpLnNwbGl0KCkpCiAgICAgICAgaWYgbm90IGJhc2U6CiAgICAgICAgICAgIHJldHVybiAiIgogICAgICAgIGlmIGJhc2VbLTFd
IG5vdCBpbiAiLiE/IjoKICAgICAgICAgICAgYmFzZSArPSAiLiIKCiAgICAgICAgIyBLZWVwIGl0IHJlYWRhYmxlIGFuZCBsaWdodGx5IHJvYm90aWMuCiAg
ICAgICAgYmFzZSA9IGJhc2UucmVwbGFjZSgiLi4uIiwgIi4iKQogICAgICAgIGJhc2UgPSBiYXNlLnJlcGxhY2UoIuKAlCIsICIsICIpCiAgICAgICAgcmV0
dXJuIGYiYmVlcC4ge2Jhc2V9IgoKICAgIGRlZiBfdG9fcm9ib3Rfc3NtbChzZWxmLCB0ZXh0KToKICAgICAgICBzYWZlID0gaHRtbC5lc2NhcGUoc2VsZi5f
cm9ib3RpY2l6ZV92b2ljZV90ZXh0KHRleHQpKQogICAgICAgIHJldHVybiAoCiAgICAgICAgICAgICc8c3BlYWsgdmVyc2lvbj0iMS4wIiB4bWw6bGFuZz0i
ZW4tVVMiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzEwL3N5bnRoZXNpcyI+JwogICAgICAgICAgICAnPHByb3NvZHkgcGl0Y2g9Ii0xOCUiIHJh
dGU9Ii00JSI+JwogICAgICAgICAgICAnPGJyZWFrIHRpbWU9IjU1bXMiLz4nCiAgICAgICAgICAgIGYie3NhZmV9IgogICAgICAgICAgICAnPGJyZWFrIHRp
bWU9IjcwbXMiLz4nCiAgICAgICAgICAgICI8L3Byb3NvZHk+IgogICAgICAgICAgICAiPC9zcGVhaz4iCiAgICAgICAgKQoKICAgIGRlZiBfc3BlYWtfd2lu
ZG93cyhzZWxmLCB0ZXh0KToKICAgICAgICBzc21sID0gc2VsZi5fdG9fcm9ib3Rfc3NtbCh0ZXh0KQogICAgICAgIHNjcmlwdCA9ICgKICAgICAgICAgICAg
IiRpbnB1dFRleHQ9W0NvbnNvbGVdOjpJbi5SZWFkVG9FbmQoKTsgIgogICAgICAgICAgICAiQWRkLVR5cGUgLUFzc2VtYmx5TmFtZSBTeXN0ZW0uU3BlZWNo
OyAiCiAgICAgICAgICAgICIkcz1OZXctT2JqZWN0IFN5c3RlbS5TcGVlY2guU3ludGhlc2lzLlNwZWVjaFN5bnRoZXNpemVyOyAiCiAgICAgICAgICAgIGYi
JHMuUmF0ZT17aW50KHNlbGYuY2ZnLmdldCgndm9pY2VfcmF0ZScsIDEpKX07ICIKICAgICAgICAgICAgIiRzLlZvbHVtZT0xMDA7ICIKICAgICAgICAgICAg
InRyeSB7ICRzLlNlbGVjdFZvaWNlQnlIaW50cyhbU3lzdGVtLlNwZWVjaC5TeW50aGVzaXMuVm9pY2VHZW5kZXJdOjpNYWxlLFtTeXN0ZW0uU3BlZWNoLlN5
bnRoZXNpcy5Wb2ljZUFnZV06OkFkdWx0KSB9ICIKICAgICAgICAgICAgImNhdGNoIHsgdHJ5IHsgJHMuU2VsZWN0Vm9pY2VCeUhpbnRzKFtTeXN0ZW0uU3Bl
ZWNoLlN5bnRoZXNpcy5Wb2ljZUdlbmRlcl06Ok5ldXRyYWwsW1N5c3RlbS5TcGVlY2guU3ludGhlc2lzLlZvaWNlQWdlXTo6QWR1bHQpIH0gY2F0Y2gge30g
fSA7ICIKICAgICAgICAgICAgInRyeSB7ICRzLlNwZWFrU3NtbCgkaW5wdXRUZXh0KSB9IGNhdGNoIHsgJHBsYWluPVtyZWdleF06OlJlcGxhY2UoJGlucHV0
VGV4dCwnPFtePl0rPicsJyAnKTsgJHMuU3BlYWsoJHBsYWluKSB9IgogICAgICAgICkKICAgICAgICB0cnk6CiAgICAgICAgICAgIHN1YnByb2Nlc3MucnVu
KAogICAgICAgICAgICAgICAgWyJwb3dlcnNoZWxsIiwgIi1Ob1Byb2ZpbGUiLCAiLUNvbW1hbmQiLCBzY3JpcHRdLAogICAgICAgICAgICAgICAgaW5wdXQ9
c3NtbCwKICAgICAgICAgICAgICAgIHRleHQ9VHJ1ZSwKICAgICAgICAgICAgICAgIGNhcHR1cmVfb3V0cHV0PVRydWUsCiAgICAgICAgICAgICAgICB0aW1l
b3V0PTQ1LAogICAgICAgICAgICAgICAgY2hlY2s9RmFsc2UsCiAgICAgICAgICAgICkKICAgICAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgICAgICBw
YXNzCgogICAgZGVmIF9zZXRfY2hhdF9zdGF0dXMoc2VsZiwgdGV4dCk6CiAgICAgICAgc3RhdHVzX3ZhciA9IHNlbGYuY2hhdF93aWRnZXRzLmdldCgic3Rh
dHVzIikKICAgICAgICBpZiBzdGF0dXNfdmFyIGlzIG5vdCBOb25lOgogICAgICAgICAgICBzdGF0dXNfdmFyLnNldCh0ZXh0KQoKICAgIGRlZiBfc2V0X2No
YXRfYnVzeShzZWxmLCBidXN5KToKICAgICAgICBzZWxmLmNoYXRfYnVzeSA9IGJ1c3kKICAgICAgICBzZW5kX2J0biA9IHNlbGYuY2hhdF93aWRnZXRzLmdl
dCgic2VuZCIpCiAgICAgICAgZW50cnkgPSBzZWxmLmNoYXRfd2lkZ2V0cy5nZXQoImVudHJ5IikKICAgICAgICBpZiBzZW5kX2J0biBpcyBub3QgTm9uZSBh
bmQgc2VuZF9idG4ud2luZm9fZXhpc3RzKCk6CiAgICAgICAgICAgIHNlbmRfYnRuLmNvbmZpZ3VyZShzdGF0ZT0oImRpc2FibGVkIiBpZiBidXN5IGVsc2Ug
Im5vcm1hbCIpKQogICAgICAgIGlmIGVudHJ5IGlzIG5vdCBOb25lIGFuZCBlbnRyeS53aW5mb19leGlzdHMoKToKICAgICAgICAgICAgZW50cnkuY29uZmln
dXJlKHN0YXRlPSgiZGlzYWJsZWQiIGlmIGJ1c3kgZWxzZSAibm9ybWFsIikpCiAgICAgICAgICAgIGlmIG5vdCBidXN5OgogICAgICAgICAgICAgICAgZW50
cnkuZm9jdXNfc2V0KCkKCiAgICBkZWYgX2FwcGVuZF9jaGF0X2xpbmUoc2VsZiwgc3BlYWtlciwgdGV4dCk6CiAgICAgICAgbGluZSA9IGYie3NwZWFrZXJ9
OiB7dGV4dH0iCiAgICAgICAgc2VsZi5jaGF0X2hpc3RvcnkuYXBwZW5kKGxpbmUpCiAgICAgICAgc2VsZi5jaGF0X2hpc3RvcnkgPSBzZWxmLmNoYXRfaGlz
dG9yeVstMTIwOl0KCiAgICAgICAgdGV4dF93aWRnZXQgPSBzZWxmLmNoYXRfd2lkZ2V0cy5nZXQoImxvZyIpCiAgICAgICAgaWYgdGV4dF93aWRnZXQgaXMg
Tm9uZSBvciBub3QgdGV4dF93aWRnZXQud2luZm9fZXhpc3RzKCk6CiAgICAgICAgICAgIHJldHVybgoKICAgICAgICB0ZXh0X3dpZGdldC5jb25maWd1cmUo
c3RhdGU9Im5vcm1hbCIpCiAgICAgICAgdGV4dF93aWRnZXQuaW5zZXJ0KCJlbmQiLCBsaW5lICsgIlxuIikKICAgICAgICB0ZXh0X3dpZGdldC5zZWUoImVu
ZCIpCiAgICAgICAgdGV4dF93aWRnZXQuY29uZmlndXJlKHN0YXRlPSJkaXNhYmxlZCIpCgogICAgZGVmIF9zdGFydF9hc3Npc3RhbnRfc3RyZWFtKHNlbGYp
OgogICAgICAgIHNlbGYuY2hhdF9zdHJlYW1fdGV4dCA9ICIiCiAgICAgICAgc2VsZi5jaGF0X3N0cmVhbV9pbl93aWRnZXQgPSBGYWxzZQogICAgICAgIHRl
eHRfd2lkZ2V0ID0gc2VsZi5jaGF0X3dpZGdldHMuZ2V0KCJsb2ciKQogICAgICAgIGlmIHRleHRfd2lkZ2V0IGlzIE5vbmUgb3Igbm90IHRleHRfd2lkZ2V0
LndpbmZvX2V4aXN0cygpOgogICAgICAgICAgICByZXR1cm4KICAgICAgICB0ZXh0X3dpZGdldC5jb25maWd1cmUoc3RhdGU9Im5vcm1hbCIpCiAgICAgICAg
dGV4dF93aWRnZXQuaW5zZXJ0KCJlbmQiLCAiQnl0ZTogIikKICAgICAgICB0ZXh0X3dpZGdldC5zZWUoImVuZCIpCiAgICAgICAgdGV4dF93aWRnZXQuY29u
ZmlndXJlKHN0YXRlPSJkaXNhYmxlZCIpCiAgICAgICAgc2VsZi5jaGF0X3N0cmVhbV9pbl93aWRnZXQgPSBUcnVlCgogICAgZGVmIF9hcHBlbmRfYXNzaXN0
YW50X3N0cmVhbShzZWxmLCBkZWx0YSk6CiAgICAgICAgaWYgbm90IGRlbHRhOgogICAgICAgICAgICByZXR1cm4KICAgICAgICBzZWxmLmNoYXRfc3RyZWFt
X3RleHQgKz0gZGVsdGEKICAgICAgICB0ZXh0X3dpZGdldCA9IHNlbGYuY2hhdF93aWRnZXRzLmdldCgibG9nIikKICAgICAgICBpZiBub3Qgc2VsZi5jaGF0
X3N0cmVhbV9pbl93aWRnZXQ6CiAgICAgICAgICAgIHJldHVybgogICAgICAgIGlmIHRleHRfd2lkZ2V0IGlzIE5vbmUgb3Igbm90IHRleHRfd2lkZ2V0Lndp
bmZvX2V4aXN0cygpOgogICAgICAgICAgICBzZWxmLmNoYXRfc3RyZWFtX2luX3dpZGdldCA9IEZhbHNlCiAgICAgICAgICAgIHJldHVybgogICAgICAgIHRl
eHRfd2lkZ2V0LmNvbmZpZ3VyZShzdGF0ZT0ibm9ybWFsIikKICAgICAgICB0ZXh0X3dpZGdldC5pbnNlcnQoImVuZCIsIGRlbHRhKQogICAgICAgIHRleHRf
d2lkZ2V0LnNlZSgiZW5kIikKICAgICAgICB0ZXh0X3dpZGdldC5jb25maWd1cmUoc3RhdGU9ImRpc2FibGVkIikKCiAgICBkZWYgX2ZpbmlzaF9hc3Npc3Rh
bnRfc3RyZWFtKHNlbGYpOgogICAgICAgIGZpbmFsX3RleHQgPSAiICIuam9pbihzZWxmLmNoYXRfc3RyZWFtX3RleHQuc3BsaXQoKSkuc3RyaXAoKQogICAg
ICAgIGlmIHNlbGYuY2hhdF9zdHJlYW1faW5fd2lkZ2V0OgogICAgICAgICAgICB0ZXh0X3dpZGdldCA9IHNlbGYuY2hhdF93aWRnZXRzLmdldCgibG9nIikK
ICAgICAgICAgICAgaWYgdGV4dF93aWRnZXQgaXMgbm90IE5vbmUgYW5kIHRleHRfd2lkZ2V0LndpbmZvX2V4aXN0cygpOgogICAgICAgICAgICAgICAgdGV4
dF93aWRnZXQuY29uZmlndXJlKHN0YXRlPSJub3JtYWwiKQogICAgICAgICAgICAgICAgdGV4dF93aWRnZXQuaW5zZXJ0KCJlbmQiLCAiXG4iKQogICAgICAg
ICAgICAgICAgdGV4dF93aWRnZXQuc2VlKCJlbmQiKQogICAgICAgICAgICAgICAgdGV4dF93aWRnZXQuY29uZmlndXJlKHN0YXRlPSJkaXNhYmxlZCIpCiAg
ICAgICAgICAgIGlmIGZpbmFsX3RleHQ6CiAgICAgICAgICAgICAgICBzZWxmLmNoYXRfaGlzdG9yeS5hcHBlbmQoZiJCeXRlOiB7ZmluYWxfdGV4dH0iKQog
ICAgICAgICAgICAgICAgc2VsZi5jaGF0X2hpc3RvcnkgPSBzZWxmLmNoYXRfaGlzdG9yeVstMTIwOl0KICAgICAgICBlbGlmIGZpbmFsX3RleHQ6CiAgICAg
ICAgICAgIHNlbGYuX2FwcGVuZF9jaGF0X2xpbmUoIkJ5dGUiLCBmaW5hbF90ZXh0KQoKICAgICAgICBzZWxmLmNoYXRfc3RyZWFtX3RleHQgPSAiIgogICAg
ICAgIHNlbGYuY2hhdF9zdHJlYW1faW5fd2lkZ2V0ID0gRmFsc2UKCiAgICBkZWYgX2V4dHJhY3RfdHRzX3NlZ21lbnRzKHNlbGYsIGJ1ZmZlcl90ZXh0LCBm
aW5hbD1GYWxzZSk6CiAgICAgICAgc2VnbWVudHMgPSBbXQogICAgICAgIHJlbWFpbmluZyA9IGJ1ZmZlcl90ZXh0CgogICAgICAgIHdoaWxlIFRydWU6CiAg
ICAgICAgICAgIHNwbGl0X2luZGV4ID0gLTEKICAgICAgICAgICAgZm9yIGlkeCwgY2ggaW4gZW51bWVyYXRlKHJlbWFpbmluZyk6CiAgICAgICAgICAgICAg
ICBpZiBjaCBpbiAiLiE/O1xuIiBhbmQgaWR4ID49IDY6CiAgICAgICAgICAgICAgICAgICAgc3BsaXRfaW5kZXggPSBpZHgKICAgICAgICAgICAgICAgICAg
ICBicmVhawogICAgICAgICAgICBpZiBzcGxpdF9pbmRleCA8IDA6CiAgICAgICAgICAgICAgICBicmVhawogICAgICAgICAgICBwaWVjZSA9IHJlbWFpbmlu
Z1s6IHNwbGl0X2luZGV4ICsgMV0uc3RyaXAoKQogICAgICAgICAgICByZW1haW5pbmcgPSByZW1haW5pbmdbc3BsaXRfaW5kZXggKyAxIDpdLmxzdHJpcCgp
CiAgICAgICAgICAgIGlmIHBpZWNlOgogICAgICAgICAgICAgICAgc2VnbWVudHMuYXBwZW5kKHBpZWNlKQoKICAgICAgICBpZiBub3QgZmluYWwgYW5kIGxl
bihyZW1haW5pbmcpID4gOTA6CiAgICAgICAgICAgIGN1dCA9IHJlbWFpbmluZy5yZmluZCgiICIsIDAsIDcwKQogICAgICAgICAgICBpZiBjdXQgPCAyNDoK
ICAgICAgICAgICAgICAgIGN1dCA9IDcwCiAgICAgICAgICAgIHBpZWNlID0gcmVtYWluaW5nWzpjdXRdLnN0cmlwKCkKICAgICAgICAgICAgcmVtYWluaW5n
ID0gcmVtYWluaW5nW2N1dDpdLmxzdHJpcCgpCiAgICAgICAgICAgIGlmIHBpZWNlOgogICAgICAgICAgICAgICAgc2VnbWVudHMuYXBwZW5kKHBpZWNlKQoK
ICAgICAgICBpZiBmaW5hbCBhbmQgcmVtYWluaW5nLnN0cmlwKCk6CiAgICAgICAgICAgIHNlZ21lbnRzLmFwcGVuZChyZW1haW5pbmcuc3RyaXAoKSkKICAg
ICAgICAgICAgcmVtYWluaW5nID0gIiIKCiAgICAgICAgcmV0dXJuIHNlZ21lbnRzLCByZW1haW5pbmcKCiAgICBkZWYgX3N1Ym1pdF9jaGF0KHNlbGYsIF9l
dmVudD1Ob25lKToKICAgICAgICBpZiBzZWxmLmNoYXRfYnVzeToKICAgICAgICAgICAgcmV0dXJuICJicmVhayIKICAgICAgICBlbnRyeSA9IHNlbGYuY2hh
dF93aWRnZXRzLmdldCgiZW50cnkiKQogICAgICAgIGlmIGVudHJ5IGlzIE5vbmUgb3Igbm90IGVudHJ5LndpbmZvX2V4aXN0cygpOgogICAgICAgICAgICBy
ZXR1cm4gImJyZWFrIgoKICAgICAgICB1c2VyX3RleHQgPSBlbnRyeS5nZXQoKS5zdHJpcCgpCiAgICAgICAgaWYgbm90IHVzZXJfdGV4dDoKICAgICAgICAg
ICAgcmV0dXJuICJicmVhayIKICAgICAgICBlbnRyeS5kZWxldGUoMCwgImVuZCIpCgogICAgICAgIHNlbGYuX2FwcGVuZF9jaGF0X2xpbmUoIllvdSIsIHVz
ZXJfdGV4dCkKICAgICAgICBzZWxmLl9zZXRfY2hhdF9idXN5KFRydWUpCiAgICAgICAgc2VsZi5fc2V0X2NoYXRfc3RhdHVzKGYiU3RyZWFtaW5nIHdpdGgg
e09MTEFNQV9NT0RFTH0uLi4iKQoKICAgICAgICB0aHJlYWQgPSB0aHJlYWRpbmcuVGhyZWFkKHRhcmdldD1zZWxmLl9jaGF0X3dvcmtlciwgYXJncz0odXNl
cl90ZXh0LCksIGRhZW1vbj1UcnVlKQogICAgICAgIHRocmVhZC5zdGFydCgpCiAgICAgICAgcmV0dXJuICJicmVhayIKCiAgICBkZWYgX2NoYXRfd29ya2Vy
KHNlbGYsIHVzZXJfdGV4dCk6CiAgICAgICAgdHJ5OgogICAgICAgICAgICBzZWxmLmNoYXRfcXVldWUucHV0KCgic3RyZWFtX3N0YXJ0IiwgTm9uZSkpCgog
ICAgICAgICAgICB0dHNfYnVmZmVyID0gIiIKICAgICAgICAgICAgc3BlYWtfZW5hYmxlZCA9IGJvb2woc2VsZi5jZmcuZ2V0KCJzcGVha19yZXBsaWVzIiwg
VHJ1ZSkpCiAgICAgICAgICAgIGZvciBkZWx0YSBpbiBzZWxmLl9zdHJlYW1fb2xsYW1hKHVzZXJfdGV4dCk6CiAgICAgICAgICAgICAgICBpZiBub3QgZGVs
dGE6CiAgICAgICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAgICAgIHNlbGYuY2hhdF9xdWV1ZS5wdXQoKCJzdHJlYW1fZGVsdGEiLCBkZWx0
YSkpCiAgICAgICAgICAgICAgICBpZiBzcGVha19lbmFibGVkOgogICAgICAgICAgICAgICAgICAgIHR0c19idWZmZXIgKz0gZGVsdGEKICAgICAgICAgICAg
ICAgICAgICBzcGVha19zZWdtZW50cywgdHRzX2J1ZmZlciA9IHNlbGYuX2V4dHJhY3RfdHRzX3NlZ21lbnRzKHR0c19idWZmZXIsIGZpbmFsPUZhbHNlKQog
ICAgICAgICAgICAgICAgICAgIGZvciBzZWdtZW50IGluIHNwZWFrX3NlZ21lbnRzOgogICAgICAgICAgICAgICAgICAgICAgICBzZWxmLnZvaWNlX3F1ZXVl
LnB1dChzZWdtZW50KQoKICAgICAgICAgICAgaWYgc3BlYWtfZW5hYmxlZDoKICAgICAgICAgICAgICAgIHRhaWxfc2VnbWVudHMsIF8gPSBzZWxmLl9leHRy
YWN0X3R0c19zZWdtZW50cyh0dHNfYnVmZmVyLCBmaW5hbD1UcnVlKQogICAgICAgICAgICAgICAgZm9yIHNlZ21lbnQgaW4gdGFpbF9zZWdtZW50czoKICAg
ICAgICAgICAgICAgICAgICBzZWxmLnZvaWNlX3F1ZXVlLnB1dChzZWdtZW50KQoKICAgICAgICAgICAgc2VsZi5jaGF0X3F1ZXVlLnB1dCgoInN0cmVhbV9l
bmQiLCBOb25lKSkKICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGV4YzoKICAgICAgICAgICAgc2VsZi5jaGF0X3F1ZXVlLnB1dCgoInN0cmVhbV9lcnJv
ciIsIHN0cihleGMpKSkKCiAgICBkZWYgX29sbGFtYV9hcGlfdXJsKHNlbGYsIHBhdGgpOgogICAgICAgIGJhc2UgPSBPTExBTUFfQ0hBVF9VUkwKICAgICAg
ICBpZiAiL2FwaS8iIGluIGJhc2U6CiAgICAgICAgICAgIGJhc2UgPSBiYXNlLnNwbGl0KCIvYXBpLyIsIDEpWzBdCiAgICAgICAgcmV0dXJuIGJhc2UucnN0
cmlwKCIvIikgKyBwYXRoCgogICAgZGVmIF9vbGxhbWFfcmVhZF9qc29uKHNlbGYsIHVybCwgcGF5bG9hZD1Ob25lLCB0aW1lb3V0PTEyMCk6CiAgICAgICAg
ZGF0YSA9IE5vbmUKICAgICAgICBtZXRob2QgPSAiR0VUIgogICAgICAgIGhlYWRlcnMgPSB7fQogICAgICAgIGlmIHBheWxvYWQgaXMgbm90IE5vbmU6CiAg
ICAgICAgICAgIG1ldGhvZCA9ICJQT1NUIgogICAgICAgICAgICBoZWFkZXJzWyJDb250ZW50LVR5cGUiXSA9ICJhcHBsaWNhdGlvbi9qc29uIgogICAgICAg
ICAgICBkYXRhID0ganNvbi5kdW1wcyhwYXlsb2FkKS5lbmNvZGUoInV0Zi04IikKCiAgICAgICAgcmVxID0gdXJsbGliLnJlcXVlc3QuUmVxdWVzdCh1cmws
IGRhdGE9ZGF0YSwgaGVhZGVycz1oZWFkZXJzLCBtZXRob2Q9bWV0aG9kKQogICAgICAgIHdpdGggdXJsbGliLnJlcXVlc3QudXJsb3BlbihyZXEsIHRpbWVv
dXQ9dGltZW91dCkgYXMgcmVzcDoKICAgICAgICAgICAgYm9keSA9IHJlc3AucmVhZCgpLmRlY29kZSgidXRmLTgiLCBlcnJvcnM9InJlcGxhY2UiKQogICAg
ICAgIHJldHVybiBqc29uLmxvYWRzKGJvZHkpCgogICAgZGVmIF9vbGxhbWFfbW9kZWxfYXZhaWxhYmxlKHNlbGYpOgogICAgICAgIHRyeToKICAgICAgICAg
ICAgZGF0YSA9IHNlbGYuX29sbGFtYV9yZWFkX2pzb24oc2VsZi5fb2xsYW1hX2FwaV91cmwoIi9hcGkvdGFncyIpLCB0aW1lb3V0PTIwKQogICAgICAgIGV4
Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgIHJldHVybiBGYWxzZQoKICAgICAgICBtb2RlbHMgPSBkYXRhLmdldCgibW9kZWxzIiwgW10pIGlmIGlzaW5z
dGFuY2UoZGF0YSwgZGljdCkgZWxzZSBbXQogICAgICAgIHdhbnQgPSBPTExBTUFfTU9ERUwubG93ZXIoKQogICAgICAgIGZvciBpdGVtIGluIG1vZGVsczoK
ICAgICAgICAgICAgaWYgbm90IGlzaW5zdGFuY2UoaXRlbSwgZGljdCk6CiAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICBuYW1lID0gc3Ry
KGl0ZW0uZ2V0KCJuYW1lIiwgIiIpKS5sb3dlcigpCiAgICAgICAgICAgIG1vZGVsID0gc3RyKGl0ZW0uZ2V0KCJtb2RlbCIsICIiKSkubG93ZXIoKQogICAg
ICAgICAgICBpZiBuYW1lID09IHdhbnQgb3IgbW9kZWwgPT0gd2FudDoKICAgICAgICAgICAgICAgIHJldHVybiBUcnVlCiAgICAgICAgcmV0dXJuIEZhbHNl
CgogICAgZGVmIF9lbnN1cmVfb2xsYW1hX21vZGVsKHNlbGYpOgogICAgICAgIHdpdGggc2VsZi5vbGxhbWFfbW9kZWxfbG9jazoKICAgICAgICAgICAgaWYg
c2VsZi5vbGxhbWFfbW9kZWxfcmVhZHk6CiAgICAgICAgICAgICAgICByZXR1cm4KCiAgICAgICAgICAgIGlmIHNlbGYuX29sbGFtYV9tb2RlbF9hdmFpbGFi
bGUoKToKICAgICAgICAgICAgICAgIHNlbGYub2xsYW1hX21vZGVsX3JlYWR5ID0gVHJ1ZQogICAgICAgICAgICAgICAgcmV0dXJuCgogICAgICAgICAgICBw
dWxsX3BheWxvYWQgPSB7Im5hbWUiOiBPTExBTUFfTU9ERUwsICJzdHJlYW0iOiBGYWxzZX0KICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgcmVz
dWx0ID0gc2VsZi5fb2xsYW1hX3JlYWRfanNvbihzZWxmLl9vbGxhbWFfYXBpX3VybCgiL2FwaS9wdWxsIiksIHBheWxvYWQ9cHVsbF9wYXlsb2FkLCB0aW1l
b3V0PTE4MDApCiAgICAgICAgICAgIGV4Y2VwdCB1cmxsaWIuZXJyb3IuVVJMRXJyb3IgYXMgZXhjOgogICAgICAgICAgICAgICAgcmFpc2UgUnVudGltZUVy
cm9yKGYiT2xsYW1hIHVuYXZhaWxhYmxlIGF0IHtPTExBTUFfQ0hBVF9VUkx9OiB7ZXhjfSIpIGZyb20gZXhjCiAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRp
b24gYXMgZXhjOgogICAgICAgICAgICAgICAgcmFpc2UgUnVudGltZUVycm9yKGYiRmFpbGVkIHRvIHB1bGwgbW9kZWwge09MTEFNQV9NT0RFTH06IHtleGN9
IikgZnJvbSBleGMKCiAgICAgICAgICAgIGlmIGlzaW5zdGFuY2UocmVzdWx0LCBkaWN0KSBhbmQgcmVzdWx0LmdldCgiZXJyb3IiKToKICAgICAgICAgICAg
ICAgIHJhaXNlIFJ1bnRpbWVFcnJvcihmIk9sbGFtYSBwdWxsIGVycm9yOiB7cmVzdWx0LmdldCgnZXJyb3InKX0iKQoKICAgICAgICAgICAgaWYgbm90IHNl
bGYuX29sbGFtYV9tb2RlbF9hdmFpbGFibGUoKToKICAgICAgICAgICAgICAgIHJhaXNlIFJ1bnRpbWVFcnJvcihmIk1vZGVsIHtPTExBTUFfTU9ERUx9IGlz
IHN0aWxsIHVuYXZhaWxhYmxlIGFmdGVyIHB1bGwuIikKCiAgICAgICAgICAgIHNlbGYub2xsYW1hX21vZGVsX3JlYWR5ID0gVHJ1ZQoKICAgIGRlZiBfc3Ry
ZWFtX29sbGFtYShzZWxmLCB1c2VyX3RleHQpOgogICAgICAgIHNlbGYuX2Vuc3VyZV9vbGxhbWFfbW9kZWwoKQoKICAgICAgICBwYXlsb2FkID0gewogICAg
ICAgICAgICAibW9kZWwiOiBPTExBTUFfTU9ERUwsCiAgICAgICAgICAgICJzdHJlYW0iOiBUcnVlLAogICAgICAgICAgICAibWVzc2FnZXMiOiBbCiAgICAg
ICAgICAgICAgICB7InJvbGUiOiAic3lzdGVtIiwgImNvbnRlbnQiOiBBSV9TWVNURU1fUFJPTVBUfSwKICAgICAgICAgICAgICAgIHsicm9sZSI6ICJ1c2Vy
IiwgImNvbnRlbnQiOiB1c2VyX3RleHR9LAogICAgICAgICAgICBdLAogICAgICAgIH0KCiAgICAgICAgcmVxID0gdXJsbGliLnJlcXVlc3QuUmVxdWVzdCgK
ICAgICAgICAgICAgT0xMQU1BX0NIQVRfVVJMLAogICAgICAgICAgICBkYXRhPWpzb24uZHVtcHMocGF5bG9hZCkuZW5jb2RlKCJ1dGYtOCIpLAogICAgICAg
ICAgICBoZWFkZXJzPXsiQ29udGVudC1UeXBlIjogImFwcGxpY2F0aW9uL2pzb24ifSwKICAgICAgICAgICAgbWV0aG9kPSJQT1NUIiwKICAgICAgICApCgog
ICAgICAgIHRyeToKICAgICAgICAgICAgd2l0aCB1cmxsaWIucmVxdWVzdC51cmxvcGVuKHJlcSwgdGltZW91dD0zMDApIGFzIHJlc3A6CiAgICAgICAgICAg
ICAgICBmb3IgcmF3X2xpbmUgaW4gcmVzcDoKICAgICAgICAgICAgICAgICAgICBsaW5lID0gcmF3X2xpbmUuZGVjb2RlKCJ1dGYtOCIsIGVycm9ycz0icmVw
bGFjZSIpLnN0cmlwKCkKICAgICAgICAgICAgICAgICAgICBpZiBub3QgbGluZToKICAgICAgICAgICAgICAgICAgICAgICAgY29udGludWUKCiAgICAgICAg
ICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgICAgICAgICBkYXRhID0ganNvbi5sb2FkcyhsaW5lKQogICAgICAgICAgICAgICAgICAgIGV4Y2Vw
dCBqc29uLkpTT05EZWNvZGVFcnJvcjoKICAgICAgICAgICAgICAgICAgICAgICAgY29udGludWUKCiAgICAgICAgICAgICAgICAgICAgaWYgaXNpbnN0YW5j
ZShkYXRhLCBkaWN0KSBhbmQgZGF0YS5nZXQoImVycm9yIik6CiAgICAgICAgICAgICAgICAgICAgICAgIHJhaXNlIFJ1bnRpbWVFcnJvcihmIk9sbGFtYSBl
cnJvcjoge2RhdGEuZ2V0KCdlcnJvcicpfSIpCgogICAgICAgICAgICAgICAgICAgIGNodW5rID0gIiIKICAgICAgICAgICAgICAgICAgICBpZiBpc2luc3Rh
bmNlKGRhdGEsIGRpY3QpOgogICAgICAgICAgICAgICAgICAgICAgICBtc2cgPSBkYXRhLmdldCgibWVzc2FnZSIpCiAgICAgICAgICAgICAgICAgICAgICAg
IGlmIGlzaW5zdGFuY2UobXNnLCBkaWN0KToKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNodW5rID0gbXNnLmdldCgiY29udGVudCIpIG9yICIiCiAg
ICAgICAgICAgICAgICAgICAgICAgIGlmIG5vdCBjaHVuazoKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNodW5rID0gZGF0YS5nZXQoInJlc3BvbnNl
Iikgb3IgIiIKCiAgICAgICAgICAgICAgICAgICAgaWYgY2h1bms6CiAgICAgICAgICAgICAgICAgICAgICAgIHlpZWxkIGNodW5rCgogICAgICAgICAgICAg
ICAgICAgIGlmIGlzaW5zdGFuY2UoZGF0YSwgZGljdCkgYW5kIGRhdGEuZ2V0KCJkb25lIik6CiAgICAgICAgICAgICAgICAgICAgICAgIGJyZWFrCiAgICAg
ICAgZXhjZXB0IHVybGxpYi5lcnJvci5VUkxFcnJvciBhcyBleGM6CiAgICAgICAgICAgIHJhaXNlIFJ1bnRpbWVFcnJvcihmIk9sbGFtYSB1bmF2YWlsYWJs
ZSBhdCB7T0xMQU1BX0NIQVRfVVJMfToge2V4Y30iKSBmcm9tIGV4YwoKICAgIGRlZiBfdXBkYXRlX21vdGlvbihzZWxmLCBkdCwgcG9pbnRlcl94LCBwb2lu
dGVyX3kpOgogICAgICAgIGlmIHNlbGYuZHJhZ2dpbmcgb3Igc2VsZi5wYXVzZWQgb3IgcG9pbnRlcl94IGlzIE5vbmUgb3IgcG9pbnRlcl95IGlzIE5vbmU6
CiAgICAgICAgICAgIHNlbGYudnggKj0gMC45CiAgICAgICAgICAgIHNlbGYudnkgKj0gMC45CiAgICAgICAgICAgIHNlbGYudHVybiAqPSAwLjkyCiAgICAg
ICAgICAgIHJldHVybgoKICAgICAgICB3LCBfID0gc2VsZi5fcGV0X3NpemUoKQogICAgICAgIGNlbnRlcl94ID0gc2VsZi54ICsgKHcgKiAwLjUpCiAgICAg
ICAgY3Vyc29yX2R4ID0gcG9pbnRlcl94IC0gY2VudGVyX3gKICAgICAgICB0dXJuX3RhcmdldCA9IGNsYW1wKGN1cnNvcl9keCAvIG1heCg0MC4wLCAodyAq
IDAuNDUpKSwgLTEuMCwgMS4wKQogICAgICAgIHNlbGYudHVybiArPSAodHVybl90YXJnZXQgLSBzZWxmLnR1cm4pICogY2xhbXAoZHQgKiAxMC4wLCAwLjAs
IDEuMCkKICAgICAgICBpZiBhYnMoY3Vyc29yX2R4KSA+IDQ6CiAgICAgICAgICAgIHNlbGYuZmFjaW5nID0gMSBpZiBjdXJzb3JfZHggPiAwIGVsc2UgLTEK
CiAgICAgICAgdGFyZ2V0X3ggPSBwb2ludGVyX3ggLSAodyAqIDAuNSkgKyBmbG9hdChzZWxmLmNmZ1siZm9sbG93X29mZnNldF94Il0pCiAgICAgICAgdGFy
Z2V0X3kgPSBwb2ludGVyX3kgKyBmbG9hdChzZWxmLmNmZ1siZm9sbG93X29mZnNldF95Il0pCgogICAgICAgIGR4ID0gdGFyZ2V0X3ggLSBzZWxmLngKICAg
ICAgICBkeSA9IHRhcmdldF95IC0gc2VsZi55CiAgICAgICAgZGlzdGFuY2UgPSBtYXRoLmh5cG90KGR4LCBkeSkKCiAgICAgICAgc3RvcF9yYWRpdXMgPSBm
bG9hdChzZWxmLmNmZ1sic3RvcF9yYWRpdXMiXSkgKiBmbG9hdChzZWxmLmNmZ1sic2NhbGUiXSkKICAgICAgICBpZiBkaXN0YW5jZSA+IHN0b3BfcmFkaXVz
OgogICAgICAgICAgICB1eCA9IGR4IC8gZGlzdGFuY2UKICAgICAgICAgICAgdXkgPSBkeSAvIGRpc3RhbmNlCiAgICAgICAgICAgIHRhcmdldF9zcGVlZCA9
IG1pbihmbG9hdChzZWxmLmNmZ1sibWF4X3NwZWVkIl0pLCA5MC4wICsgZGlzdGFuY2UgKiAyLjgpCiAgICAgICAgICAgIGRlc2lyZWRfdnggPSB1eCAqIHRh
cmdldF9zcGVlZAogICAgICAgICAgICBkZXNpcmVkX3Z5ID0gdXkgKiB0YXJnZXRfc3BlZWQKICAgICAgICAgICAgc21vb3RoID0gY2xhbXAoZHQgKiBmbG9h
dChzZWxmLmNmZ1siYWNjZWxlcmF0aW9uIl0pLCAwLjAsIDEuMCkKICAgICAgICAgICAgc2VsZi52eCArPSAoZGVzaXJlZF92eCAtIHNlbGYudngpICogc21v
b3RoCiAgICAgICAgICAgIHNlbGYudnkgKz0gKGRlc2lyZWRfdnkgLSBzZWxmLnZ5KSAqIHNtb290aAogICAgICAgIGVsc2U6CiAgICAgICAgICAgIGRhbXAg
PSBjbGFtcCgxLjAgLSBkdCAqIGZsb2F0KHNlbGYuY2ZnWyJkYW1waW5nIl0pLCAwLjAsIDEuMCkKICAgICAgICAgICAgc2VsZi52eCAqPSBkYW1wCiAgICAg
ICAgICAgIHNlbGYudnkgKj0gZGFtcAoKICAgICAgICBzZWxmLnggKz0gc2VsZi52eCAqIGR0CiAgICAgICAgc2VsZi55ICs9IHNlbGYudnkgKiBkdAoKICAg
ICAgICBpZiBhYnMoc2VsZi52eCkgPiAxMDoKICAgICAgICAgICAgc2VsZi5mYWNpbmcgPSAxIGlmIHNlbGYudnggPiAwIGVsc2UgLTEKCiAgICAgICAgdywg
aCA9IHNlbGYuX3BldF9zaXplKCkKICAgICAgICBzY3JlZW5fdyA9IHNlbGYucm9vdC53aW5mb19zY3JlZW53aWR0aCgpCiAgICAgICAgc2NyZWVuX2ggPSBz
ZWxmLnJvb3Qud2luZm9fc2NyZWVuaGVpZ2h0KCkKICAgICAgICBzZWxmLnggPSBjbGFtcChzZWxmLngsIDAsIG1heCgwLCBzY3JlZW5fdyAtIHcpKQogICAg
ICAgIHNlbGYueSA9IGNsYW1wKHNlbGYueSwgMCwgbWF4KDAsIHNjcmVlbl9oIC0gaCkpCgogICAgZGVmIF9kcmF3X3JvYm90KHNlbGYsIHBvaW50ZXJfeCwg
cG9pbnRlcl95LCBkdCwgbm93KToKICAgICAgICB3LCBoID0gc2VsZi5fcGV0X3NpemUoKQogICAgICAgIHNlbGYucm9vdC5nZW9tZXRyeShmInt3fXh7aH0r
e2ludChzZWxmLngpfSt7aW50KHNlbGYueSl9IikKICAgICAgICBzZWxmLmNhbnZhcy5kZWxldGUoImFsbCIpCgogICAgICAgIGNvbG9ycyA9IHNlbGYuY2Zn
WyJjb2xvcnMiXQogICAgICAgIHMgPSBmbG9hdChzZWxmLmNmZ1sic2NhbGUiXSkKCiAgICAgICAgc3BlZWQgPSBtYXRoLmh5cG90KHNlbGYudngsIHNlbGYu
dnkpCiAgICAgICAgbW92aW5nID0gc3BlZWQgPiAzMC4wCgogICAgICAgIGlmIG1vdmluZzoKICAgICAgICAgICAgc2VsZi53YWxrX3BoYXNlICs9IGR0ICog
KDUuMiArIHNwZWVkIC8gMTE1LjApCiAgICAgICAgc2VsZi5pZGxlX3BoYXNlICs9IGR0ICogMS44CgogICAgICAgIGlmIHBvaW50ZXJfeCBpcyBub3QgTm9u
ZToKICAgICAgICAgICAgY3Vyc29yX2R4ID0gcG9pbnRlcl94IC0gKHNlbGYueCArIHcgKiAwLjUpCiAgICAgICAgICAgIHR1cm5fdGFyZ2V0ID0gY2xhbXAo
Y3Vyc29yX2R4IC8gbWF4KDQwLjAsICh3ICogMC40NSkpLCAtMS4wLCAxLjApCiAgICAgICAgICAgIHNlbGYudHVybiArPSAodHVybl90YXJnZXQgLSBzZWxm
LnR1cm4pICogMC4xOAogICAgICAgICAgICBpZiBhYnMoY3Vyc29yX2R4KSA+IDQ6CiAgICAgICAgICAgICAgICBzZWxmLmZhY2luZyA9IDEgaWYgY3Vyc29y
X2R4ID4gMCBlbHNlIC0xCiAgICAgICAgZmFjZSA9IHNlbGYuZmFjaW5nIGlmIHNlbGYuZmFjaW5nICE9IDAgZWxzZSAxCiAgICAgICAgdHVybl9hYnMgPSBh
YnMoc2VsZi50dXJuKQoKICAgICAgICB3YWxrX3N3aW5nID0gbWF0aC5zaW4oc2VsZi53YWxrX3BoYXNlKSBpZiBtb3ZpbmcgZWxzZSAwLjAKICAgICAgICBz
dGVwX3N0cmlkZSA9IG1hdGguc2luKHNlbGYud2Fsa19waGFzZSkgKiAzLjggaWYgbW92aW5nIGVsc2UgMC4wCiAgICAgICAgdG9yc29fc3dheSA9IChtYXRo
LnNpbihzZWxmLndhbGtfcGhhc2UgKiAyLjApICogMS42KSBpZiBtb3ZpbmcgZWxzZSAobWF0aC5zaW4oc2VsZi5pZGxlX3BoYXNlKSAqIDAuOCkKICAgICAg
ICBib2R5X2JvYl9hbXAgPSBmbG9hdChzZWxmLmNmZ1sid2Fsa19ib2JfYW1wIl0pIGlmIG1vdmluZyBlbHNlIGZsb2F0KHNlbGYuY2ZnWyJpZGxlX2JvYl9h
bXAiXSkKICAgICAgICBib2R5X2JvYiA9IG1hdGguc2luKHNlbGYud2Fsa19waGFzZSAqIDIuMCBpZiBtb3ZpbmcgZWxzZSBzZWxmLmlkbGVfcGhhc2UpICog
Ym9keV9ib2JfYW1wCiAgICAgICAgaWYgbW92aW5nOgogICAgICAgICAgICBoZWFkX2JvYiA9IG1hdGguc2luKHNlbGYud2Fsa19waGFzZSAqIDIuMSArIDAu
NTUpICogZmxvYXQoc2VsZi5jZmdbImhlYWRfYm9iX2FtcCJdKQogICAgICAgIGVsc2U6CiAgICAgICAgICAgIGhlYWRfYm9iID0gbWF0aC5zaW4oc2VsZi5p
ZGxlX3BoYXNlICogMS4zNSkgKiAoZmxvYXQoc2VsZi5jZmdbImhlYWRfYm9iX2FtcCJdKSAqIDAuNykKCiAgICAgICAgbGVhbiA9IGNsYW1wKChzZWxmLnZ4
IC8gMTI1LjApICsgKGZhY2UgKiB0b3Jzb19zd2F5ICogMC41KSArIChmYWNlICogc2VsZi50dXJuICogNS4wKSwgLTkuMCwgOS4wKQogICAgICAgIGJvZHlf
c2hpZnQgPSB0b3Jzb19zd2F5ICogMC45CiAgICAgICAgaGVhZF9zaGlmdCA9IGxlYW4gKyB0b3Jzb19zd2F5ICogMC42ICsgKGZhY2UgKiB0dXJuX2FicyAq
IDIuMCkKCiAgICAgICAgZGVmIHN4KHYpOgogICAgICAgICAgICByZXR1cm4gdiAqIHMKCiAgICAgICAgZGVmIHR4KHYpOgogICAgICAgICAgICByZXR1cm4g
diBpZiBmYWNlID4gMCBlbHNlIChCQVNFX1cgLSB2KQoKICAgICAgICBkZWYgeCh2KToKICAgICAgICAgICAgcmV0dXJuIHN4KHR4KHYpKQoKICAgICAgICBk
ZWYgeSh2KToKICAgICAgICAgICAgcmV0dXJuIHN4KHYpCgogICAgICAgIGRlZiB4cihhLCBiKToKICAgICAgICAgICAgdGEsIHRiID0gdHgoYSksIHR4KGIp
CiAgICAgICAgICAgIGlmIHRhIDw9IHRiOgogICAgICAgICAgICAgICAgcmV0dXJuIHN4KHRhKSwgc3godGIpCiAgICAgICAgICAgIHJldHVybiBzeCh0Yiks
IHN4KHRhKQoKICAgICAgICBpZiBib29sKHNlbGYuY2ZnWyJzaG93X3NoYWRvdyJdKToKICAgICAgICAgICAgc2hhZG93X3gxLCBzaGFkb3dfeDIgPSB4cig0
MiArIGJvZHlfc2hpZnQsIDEyOCArIGJvZHlfc2hpZnQpCiAgICAgICAgICAgIHNlbGYuY2FudmFzLmNyZWF0ZV9vdmFsKAogICAgICAgICAgICAgICAgc2hh
ZG93X3gxLAogICAgICAgICAgICAgICAgeSgxMzMpLAogICAgICAgICAgICAgICAgc2hhZG93X3gyLAogICAgICAgICAgICAgICAgeSgxNDkpLAogICAgICAg
ICAgICAgICAgZmlsbD1jb2xvcnNbInNoYWRvdyJdLAogICAgICAgICAgICAgICAgb3V0bGluZT0iIiwKICAgICAgICAgICAgICAgIHN0aXBwbGU9ImdyYXk1
MCIsCiAgICAgICAgICAgICkKCiAgICAgICAgbGVmdF9saWZ0ID0gbWF4KDAuMCwgd2Fsa19zd2luZykgKiBmbG9hdChzZWxmLmNmZ1sibGVnX2xpZnRfYW1w
Il0pCiAgICAgICAgcmlnaHRfbGlmdCA9IG1heCgwLjAsIC13YWxrX3N3aW5nKSAqIGZsb2F0KHNlbGYuY2ZnWyJsZWdfbGlmdF9hbXAiXSkKICAgICAgICBs
ZWdfdG9wID0gMTA4ICsgYm9keV9ib2IKCiAgICAgICAgbGVmdF9sZWdfeDEsIGxlZnRfbGVnX3gyID0geHIoNjIgKyBib2R5X3NoaWZ0ICsgc3RlcF9zdHJp
ZGUsIDc2ICsgYm9keV9zaGlmdCArIHN0ZXBfc3RyaWRlKQogICAgICAgIHJpZ2h0X2xlZ194MSwgcmlnaHRfbGVnX3gyID0geHIoOTQgKyBib2R5X3NoaWZ0
IC0gc3RlcF9zdHJpZGUsIDEwOCArIGJvZHlfc2hpZnQgLSBzdGVwX3N0cmlkZSkKICAgICAgICBzZWxmLmNhbnZhcy5jcmVhdGVfcmVjdGFuZ2xlKGxlZnRf
bGVnX3gxLCB5KGxlZ190b3AgKyBsZWZ0X2xpZnQpLCBsZWZ0X2xlZ194MiwgeSgxMzYpLCBmaWxsPWNvbG9yc1sidHJpbSJdLCBvdXRsaW5lPWNvbG9yc1si
dHJpbSJdKQogICAgICAgIHNlbGYuY2FudmFzLmNyZWF0ZV9yZWN0YW5nbGUocmlnaHRfbGVnX3gxLCB5KGxlZ190b3AgKyByaWdodF9saWZ0KSwgcmlnaHRf
bGVnX3gyLCB5KDEzNiksIGZpbGw9Y29sb3JzWyJ0cmltIl0sIG91dGxpbmU9Y29sb3JzWyJ0cmltIl0pCgogICAgICAgIGxlZnRfZm9vdF94MSwgbGVmdF9m
b290X3gyID0geHIoNTYgKyBib2R5X3NoaWZ0ICsgc3RlcF9zdHJpZGUsIDgwICsgYm9keV9zaGlmdCArIHN0ZXBfc3RyaWRlKQogICAgICAgIHJpZ2h0X2Zv
b3RfeDEsIHJpZ2h0X2Zvb3RfeDIgPSB4cig4OCArIGJvZHlfc2hpZnQgLSBzdGVwX3N0cmlkZSwgMTEyICsgYm9keV9zaGlmdCAtIHN0ZXBfc3RyaWRlKQog
ICAgICAgIHNlbGYuY2FudmFzLmNyZWF0ZV9yZWN0YW5nbGUoCiAgICAgICAgICAgIGxlZnRfZm9vdF94MSwgeSgxMzYpLCBsZWZ0X2Zvb3RfeDIsIHkoMTQ1
KSwgZmlsbD1jb2xvcnNbInBhbmVsIl0sIG91dGxpbmU9Y29sb3JzWyJ0cmltIl0sIHdpZHRoPW1heCgxLCBpbnQoMiAqIHMpKQogICAgICAgICkKICAgICAg
ICBzZWxmLmNhbnZhcy5jcmVhdGVfcmVjdGFuZ2xlKAogICAgICAgICAgICByaWdodF9mb290X3gxLCB5KDEzNiksIHJpZ2h0X2Zvb3RfeDIsIHkoMTQ1KSwg
ZmlsbD1jb2xvcnNbInBhbmVsIl0sIG91dGxpbmU9Y29sb3JzWyJ0cmltIl0sIHdpZHRoPW1heCgxLCBpbnQoMiAqIHMpKQogICAgICAgICkKCiAgICAgICAg
YXJtX2FtcCA9IGZsb2F0KHNlbGYuY2ZnWyJhcm1fc3dpbmdfYW1wIl0pCiAgICAgICAgYXJtX3N3aW5nID0gbWF0aC5zaW4oc2VsZi53YWxrX3BoYXNlICsg
MC43KSAqIGFybV9hbXAgaWYgbW92aW5nIGVsc2UgbWF0aC5zaW4oc2VsZi5pZGxlX3BoYXNlKSAqIDIuMgogICAgICAgIHNob3VsZGVyX3kgPSA4MCArIGJv
ZHlfYm9iCiAgICAgICAgc2VsZi5jYW52YXMuY3JlYXRlX2xpbmUoCiAgICAgICAgICAgIHgoMzYgKyBib2R5X3NoaWZ0KSwKICAgICAgICAgICAgeShzaG91
bGRlcl95KSwKICAgICAgICAgICAgeCgyNCArIGJvZHlfc2hpZnQgLSBzdGVwX3N0cmlkZSAqIDAuNiksCiAgICAgICAgICAgIHkoc2hvdWxkZXJfeSArIDE4
ICsgYXJtX3N3aW5nKSwKICAgICAgICAgICAgZmlsbD1jb2xvcnNbInRyaW0iXSwKICAgICAgICAgICAgd2lkdGg9bWF4KDIsIGludCg0ICogcykpLAogICAg
ICAgICAgICBjYXBzdHlsZT10ay5ST1VORCwKICAgICAgICApCiAgICAgICAgc2VsZi5jYW52YXMuY3JlYXRlX2xpbmUoCiAgICAgICAgICAgIHgoMTM0ICsg
Ym9keV9zaGlmdCksCiAgICAgICAgICAgIHkoc2hvdWxkZXJfeSksCiAgICAgICAgICAgIHgoMTQ2ICsgYm9keV9zaGlmdCArIHN0ZXBfc3RyaWRlICogMC42
KSwKICAgICAgICAgICAgeShzaG91bGRlcl95ICsgMTggLSBhcm1fc3dpbmcpLAogICAgICAgICAgICBmaWxsPWNvbG9yc1sidHJpbSJdLAogICAgICAgICAg
ICB3aWR0aD1tYXgoMiwgaW50KDQgKiBzKSksCiAgICAgICAgICAgIGNhcHN0eWxlPXRrLlJPVU5ELAogICAgICAgICkKCiAgICAgICAgYngxLCBieTEgPSAz
NCArIGJvZHlfc2hpZnQsIDY1ICsgYm9keV9ib2IKICAgICAgICBieDIsIGJ5MiA9IDEzNiArIGJvZHlfc2hpZnQsIDExNiArIGJvZHlfYm9iCiAgICAgICAg
Ym9keV94MSwgYm9keV94MiA9IHhyKGJ4MSwgYngyKQogICAgICAgIHNlbGYuY2FudmFzLmNyZWF0ZV9yZWN0YW5nbGUoCiAgICAgICAgICAgIGJvZHlfeDEs
IHkoYnkxKSwgYm9keV94MiwgeShieTIpLCBmaWxsPWNvbG9yc1siYm9keSJdLCBvdXRsaW5lPWNvbG9yc1sidHJpbSJdLCB3aWR0aD1tYXgoMiwgaW50KDMg
KiBzKSkKICAgICAgICApCiAgICAgICAgYm9keV9zaWRlX3cgPSA0ICsgKDkgKiB0dXJuX2FicykKICAgICAgICBzZWxmLmNhbnZhcy5jcmVhdGVfcG9seWdv
bigKICAgICAgICAgICAgeChieDIpLAogICAgICAgICAgICB5KGJ5MSArIDQpLAogICAgICAgICAgICB4KGJ4MiArIGJvZHlfc2lkZV93KSwKICAgICAgICAg
ICAgeShieTEgKyA5KSwKICAgICAgICAgICAgeChieDIgKyBib2R5X3NpZGVfdyksCiAgICAgICAgICAgIHkoYnkyIC0gNCksCiAgICAgICAgICAgIHgoYngy
KSwKICAgICAgICAgICAgeShieTIgLSAyKSwKICAgICAgICAgICAgZmlsbD1jb2xvcnNbInRyaW0iXSwKICAgICAgICAgICAgb3V0bGluZT1jb2xvcnNbInRy
aW0iXSwKICAgICAgICApCiAgICAgICAgcGFuZWxfeDEsIHBhbmVsX3gyID0geHIoNTAgKyBib2R5X3NoaWZ0LCAxMjAgKyBib2R5X3NoaWZ0KQogICAgICAg
IHNlbGYuY2FudmFzLmNyZWF0ZV9yZWN0YW5nbGUoCiAgICAgICAgICAgIHBhbmVsX3gxLCB5KDc1ICsgYm9keV9ib2IpLCBwYW5lbF94MiwgeSgxMDUgKyBi
b2R5X2JvYiksIGZpbGw9Y29sb3JzWyJwYW5lbCJdLCBvdXRsaW5lPWNvbG9yc1sidHJpbSJdLCB3aWR0aD1tYXgoMSwgaW50KDIgKiBzKSkKICAgICAgICAp
CiAgICAgICAgYmFkZ2VfeDEsIGJhZGdlX3gyID0geHIoNzggKyBib2R5X3NoaWZ0LCA5MiArIGJvZHlfc2hpZnQpCiAgICAgICAgc2VsZi5jYW52YXMuY3Jl
YXRlX3JlY3RhbmdsZSgKICAgICAgICAgICAgYmFkZ2VfeDEsIHkoODQgKyBib2R5X2JvYiksIGJhZGdlX3gyLCB5KDk3ICsgYm9keV9ib2IpLCBmaWxsPWNv
bG9yc1siYWNjZW50Il0sIG91dGxpbmU9Y29sb3JzWyJ0cmltIl0sIHdpZHRoPW1heCgxLCBpbnQoMiAqIHMpKQogICAgICAgICkKCiAgICAgICAgbGVkX29u
ID0gKGludChub3cgKiA2KSAlIDIpID09IDAKICAgICAgICBsZWRfbF94MSwgbGVkX2xfeDIgPSB4cig1NyArIGJvZHlfc2hpZnQsIDY1ICsgYm9keV9zaGlm
dCkKICAgICAgICBsZWRfcl94MSwgbGVkX3JfeDIgPSB4cigxMDUgKyBib2R5X3NoaWZ0LCAxMTMgKyBib2R5X3NoaWZ0KQogICAgICAgIHNlbGYuY2FudmFz
LmNyZWF0ZV9vdmFsKAogICAgICAgICAgICBsZWRfbF94MSwgeSg4NiArIGJvZHlfYm9iKSwgbGVkX2xfeDIsIHkoOTQgKyBib2R5X2JvYiksIGZpbGw9Y29s
b3JzWyJleWUiXSBpZiBsZWRfb24gZWxzZSBjb2xvcnNbInRyaW0iXSwgb3V0bGluZT1jb2xvcnNbInRyaW0iXQogICAgICAgICkKICAgICAgICBzZWxmLmNh
bnZhcy5jcmVhdGVfb3ZhbCgKICAgICAgICAgICAgbGVkX3JfeDEsIHkoODYgKyBib2R5X2JvYiksIGxlZF9yX3gyLCB5KDk0ICsgYm9keV9ib2IpLCBmaWxs
PWNvbG9yc1siZXllIl0gaWYgbm90IGxlZF9vbiBlbHNlIGNvbG9yc1sidHJpbSJdLCBvdXRsaW5lPWNvbG9yc1sidHJpbSJdCiAgICAgICAgKQoKICAgICAg
ICBuZWNrX3RpbHQgPSBjbGFtcChsZWFuICogMC40LCAtNC4wLCA0LjApCiAgICAgICAgc2VsZi5jYW52YXMuY3JlYXRlX2xpbmUoCiAgICAgICAgICAgIHgo
ODAgKyBib2R5X3NoaWZ0KSwKICAgICAgICAgICAgeSg2MyArIGJvZHlfYm9iKSwKICAgICAgICAgICAgeCg4MCArIGJvZHlfc2hpZnQgKyBuZWNrX3RpbHQp
LAogICAgICAgICAgICB5KDU0ICsgYm9keV9ib2IpLAogICAgICAgICAgICBmaWxsPWNvbG9yc1sidHJpbSJdLAogICAgICAgICAgICB3aWR0aD1tYXgoMiwg
aW50KDQgKiBzKSksCiAgICAgICAgKQogICAgICAgIHNlbGYuY2FudmFzLmNyZWF0ZV9saW5lKAogICAgICAgICAgICB4KDkwICsgYm9keV9zaGlmdCksCiAg
ICAgICAgICAgIHkoNjMgKyBib2R5X2JvYiksCiAgICAgICAgICAgIHgoOTAgKyBib2R5X3NoaWZ0ICsgbmVja190aWx0KSwKICAgICAgICAgICAgeSg1NCAr
IGJvZHlfYm9iKSwKICAgICAgICAgICAgZmlsbD1jb2xvcnNbInRyaW0iXSwKICAgICAgICAgICAgd2lkdGg9bWF4KDIsIGludCg0ICogcykpLAogICAgICAg
ICkKCiAgICAgICAgaHgxID0gNDYgKyBoZWFkX3NoaWZ0CiAgICAgICAgaHkxID0gMjIgKyBib2R5X2JvYiArIGhlYWRfYm9iCiAgICAgICAgaHgyID0gMTI0
ICsgaGVhZF9zaGlmdAogICAgICAgIGh5MiA9IDY5ICsgYm9keV9ib2IgKyBoZWFkX2JvYgogICAgICAgIGhlYWRfeDEsIGhlYWRfeDIgPSB4cihoeDEsIGh4
MikKICAgICAgICBzZWxmLmNhbnZhcy5jcmVhdGVfcmVjdGFuZ2xlKAogICAgICAgICAgICBoZWFkX3gxLCB5KGh5MSksIGhlYWRfeDIsIHkoaHkyKSwgZmls
bD1jb2xvcnNbImJvZHkiXSwgb3V0bGluZT1jb2xvcnNbInRyaW0iXSwgd2lkdGg9bWF4KDIsIGludCgzICogcykpCiAgICAgICAgKQogICAgICAgIGhlYWRf
c2lkZV93ID0gNiArICgxMSAqIHR1cm5fYWJzKQogICAgICAgIHNlbGYuY2FudmFzLmNyZWF0ZV9wb2x5Z29uKAogICAgICAgICAgICB4KGh4MiksCiAgICAg
ICAgICAgIHkoaHkxICsgNCksCiAgICAgICAgICAgIHgoaHgyICsgaGVhZF9zaWRlX3cpLAogICAgICAgICAgICB5KGh5MSArIDkpLAogICAgICAgICAgICB4
KGh4MiArIGhlYWRfc2lkZV93KSwKICAgICAgICAgICAgeShoeTIgLSA1KSwKICAgICAgICAgICAgeChoeDIpLAogICAgICAgICAgICB5KGh5MiAtIDIpLAog
ICAgICAgICAgICBmaWxsPWNvbG9yc1sidHJpbSJdLAogICAgICAgICAgICBvdXRsaW5lPWNvbG9yc1sidHJpbSJdLAogICAgICAgICkKICAgICAgICBmYWNl
X3BhbmVsX2Zhcl9pbnNldCA9IDggKyAoMTIgKiB0dXJuX2FicykKICAgICAgICBmYWNlX3BhbmVsX3gxLCBmYWNlX3BhbmVsX3gyID0geHIoaHgxICsgZmFj
ZV9wYW5lbF9mYXJfaW5zZXQsIGh4MiAtIDgpCiAgICAgICAgc2VsZi5jYW52YXMuY3JlYXRlX3JlY3RhbmdsZSgKICAgICAgICAgICAgZmFjZV9wYW5lbF94
MSwgeShoeTEgKyAxMCksIGZhY2VfcGFuZWxfeDIsIHkoaHkyIC0gOCksIGZpbGw9Y29sb3JzWyJwYW5lbCJdLCBvdXRsaW5lPWNvbG9yc1sidHJpbSJdLCB3
aWR0aD1tYXgoMSwgaW50KDIgKiBzKSkKICAgICAgICApCgogICAgICAgIHB1bHNlID0gMC41ICsgMC41ICogbWF0aC5zaW4obm93ICogNy4wKQogICAgICAg
IGFudGVubmFfZmlsbCA9IGNvbG9yc1siYWNjZW50Il0gaWYgcHVsc2UgPiAwLjM1IGVsc2UgY29sb3JzWyJ0cmltIl0KICAgICAgICBjeCA9IDg1ICsgaGVh
ZF9zaGlmdAogICAgICAgIG1vZGUgPSBpbnQoc2VsZi5jZmdbImFudGVubmFfbW9kZSJdKQogICAgICAgIGlmIG1vZGUgPT0gMDoKICAgICAgICAgICAgc2Vs
Zi5jYW52YXMuY3JlYXRlX2xpbmUoeChjeCksIHkoaHkxKSwgeChjeCksIHkoaHkxIC0gMTUpLCBmaWxsPWNvbG9yc1sidHJpbSJdLCB3aWR0aD1tYXgoMiwg
aW50KDMgKiBzKSkpCiAgICAgICAgICAgIGExLCBhMiA9IHhyKGN4IC0gNCwgY3ggKyA0KQogICAgICAgICAgICBzZWxmLmNhbnZhcy5jcmVhdGVfb3ZhbChh
MSwgeShoeTEgLSAyMCksIGEyLCB5KGh5MSAtIDEyKSwgZmlsbD1hbnRlbm5hX2ZpbGwsIG91dGxpbmU9Y29sb3JzWyJ0cmltIl0pCiAgICAgICAgZWxpZiBt
b2RlID09IDE6CiAgICAgICAgICAgIGZvciBheCBpbiAoY3ggLSAxMCwgY3ggKyAxMCk6CiAgICAgICAgICAgICAgICBzZWxmLmNhbnZhcy5jcmVhdGVfbGlu
ZSh4KGF4KSwgeShoeTEpLCB4KGF4KSwgeShoeTEgLSAxMiksIGZpbGw9Y29sb3JzWyJ0cmltIl0sIHdpZHRoPW1heCgyLCBpbnQoMyAqIHMpKSkKICAgICAg
ICAgICAgICAgIGIxLCBiMiA9IHhyKGF4IC0gMywgYXggKyAzKQogICAgICAgICAgICAgICAgc2VsZi5jYW52YXMuY3JlYXRlX292YWwoYjEsIHkoaHkxIC0g
MTYpLCBiMiwgeShoeTEgLSAxMCksIGZpbGw9YW50ZW5uYV9maWxsLCBvdXRsaW5lPWNvbG9yc1sidHJpbSJdKQogICAgICAgIGVsc2U6CiAgICAgICAgICAg
IHNlbGYuY2FudmFzLmNyZWF0ZV9saW5lKHgoY3gpLCB5KGh5MSksIHgoY3gpLCB5KGh5MSAtIDEwKSwgZmlsbD1jb2xvcnNbInRyaW0iXSwgd2lkdGg9bWF4
KDIsIGludCgzICogcykpKQogICAgICAgICAgICBhcmNfeDEsIGFyY194MiA9IHhyKGN4IC0gMTQsIGN4ICsgMTQpCiAgICAgICAgICAgIHNlbGYuY2FudmFz
LmNyZWF0ZV9hcmMoCiAgICAgICAgICAgICAgICBhcmNfeDEsCiAgICAgICAgICAgICAgICB5KGh5MSAtIDI1KSwKICAgICAgICAgICAgICAgIGFyY194MiwK
ICAgICAgICAgICAgICAgIHkoaHkxIC0gMSksCiAgICAgICAgICAgICAgICBzdGFydD0yMCwKICAgICAgICAgICAgICAgIGV4dGVudD0xNDAsCiAgICAgICAg
ICAgICAgICBzdHlsZT10ay5BUkMsCiAgICAgICAgICAgICAgICBvdXRsaW5lPWFudGVubmFfZmlsbCwKICAgICAgICAgICAgICAgIHdpZHRoPW1heCgyLCBp
bnQoMyAqIHMpKSwKICAgICAgICAgICAgKQoKICAgICAgICBpZiBwb2ludGVyX3ggaXMgTm9uZSBvciBwb2ludGVyX3kgaXMgTm9uZToKICAgICAgICAgICAg
cG9pbnRlcl94ID0gc2VsZi54ICsgdyAqIDAuNQogICAgICAgICAgICBwb2ludGVyX3kgPSBzZWxmLnkgKyBoICogMC41CgogICAgICAgIGV5ZV9zY2FsZSA9
IGZsb2F0KHNlbGYuY2ZnWyJleWVfc2NhbGUiXSkKICAgICAgICBwdXBpbF9zY2FsZSA9IGZsb2F0KHNlbGYuY2ZnWyJwdXBpbF9zY2FsZSJdKQogICAgICAg
IG5lYXJfZXllX3J4ID0gMTAuNSAqIGV5ZV9zY2FsZSAqICgxLjAgKyAwLjE2ICogdHVybl9hYnMpCiAgICAgICAgbmVhcl9leWVfcnkgPSA4LjIgKiBleWVf
c2NhbGUgKiAoMS4wICsgMC4xICogdHVybl9hYnMpCiAgICAgICAgZmFyX2V5ZV9yeCA9IG1heCg0LjIsIDEwLjAgKiBleWVfc2NhbGUgKiAoMS4wIC0gMC41
MiAqIHR1cm5fYWJzKSkKICAgICAgICBmYXJfZXllX3J5ID0gbWF4KDMuOCwgOC4wICogZXllX3NjYWxlICogKDEuMCAtIDAuNDggKiB0dXJuX2FicykpCiAg
ICAgICAgbmVhcl9wdXBpbF9yID0gbWF4KDEuNSwgMy4wICogcHVwaWxfc2NhbGUgKiAoMS4wICsgMC4xMiAqIHR1cm5fYWJzKSkKICAgICAgICBmYXJfcHVw
aWxfciA9IG1heCgxLjIsIDMuMCAqIHB1cGlsX3NjYWxlICogKDEuMCAtIDAuMjQgKiB0dXJuX2FicykpCiAgICAgICAgYmxpbmtpbmcgPSBub3cgPCBzZWxm
LmJsaW5rX2VuZAoKICAgICAgICBmYXJfZXllX2NlbnRlciA9ICg2NyArIGhlYWRfc2hpZnQgKyAoOC4wICogdHVybl9hYnMpLCA0NCArIGJvZHlfYm9iICsg
aGVhZF9ib2IpCiAgICAgICAgbmVhcl9leWVfY2VudGVyID0gKDEwMyArIGhlYWRfc2hpZnQgLSAoMy4wICogdHVybl9hYnMpLCA0NCArIGJvZHlfYm9iICsg
aGVhZF9ib2IpCgogICAgICAgIGRlZiBkcmF3X2V5ZShleCwgZXksIGV5ZV9yeCwgZXllX3J5LCBwdXBpbF9yLCB0aW50PTEuMCk6CiAgICAgICAgICAgIGV5
ZV9jeCA9IHNlbGYueCArIHgoZXgpCiAgICAgICAgICAgIGV5ZV9jeSA9IHNlbGYueSArIHkoZXkpCiAgICAgICAgICAgIGV5ZV9yeF9weCA9IGV5ZV9yeCAq
IHMKICAgICAgICAgICAgZXllX3J5X3B4ID0gZXllX3J5ICogcwogICAgICAgICAgICBwdXBpbF9yX3B4ID0gcHVwaWxfciAqIHMKCiAgICAgICAgICAgIHNl
bGYuY2FudmFzLmNyZWF0ZV9vdmFsKAogICAgICAgICAgICAgICAgZXllX2N4IC0gZXllX3J4X3B4LAogICAgICAgICAgICAgICAgZXllX2N5IC0gZXllX3J5
X3B4LAogICAgICAgICAgICAgICAgZXllX2N4ICsgZXllX3J4X3B4LAogICAgICAgICAgICAgICAgZXllX2N5ICsgZXllX3J5X3B4LAogICAgICAgICAgICAg
ICAgZmlsbD1jb2xvcnNbImV5ZSJdLAogICAgICAgICAgICAgICAgb3V0bGluZT1jb2xvcnNbInRyaW0iXSwKICAgICAgICAgICAgICAgIHdpZHRoPW1heCgx
LCBpbnQoMiAqIHMpKSwKICAgICAgICAgICAgKQogICAgICAgICAgICBpZiBibGlua2luZzoKICAgICAgICAgICAgICAgIHNlbGYuY2FudmFzLmNyZWF0ZV9s
aW5lKAogICAgICAgICAgICAgICAgICAgIGV5ZV9jeCAtIChleWVfcnggLSAyKSAqIHMsCiAgICAgICAgICAgICAgICAgICAgZXllX2N5LAogICAgICAgICAg
ICAgICAgICAgIGV5ZV9jeCArIChleWVfcnggLSAyKSAqIHMsCiAgICAgICAgICAgICAgICAgICAgZXllX2N5LAogICAgICAgICAgICAgICAgICAgIGZpbGw9
Y29sb3JzWyJ0cmltIl0sCiAgICAgICAgICAgICAgICAgICAgd2lkdGg9bWF4KDIsIGludCgzICogcykpLAogICAgICAgICAgICAgICAgKQogICAgICAgICAg
ICBlbHNlOgogICAgICAgICAgICAgICAgbWF4X29mZl94ID0gbWF4KDAuMCwgZXllX3J4X3B4IC0gcHVwaWxfcl9weCAtICgxLjYgKiBzKSkKICAgICAgICAg
ICAgICAgIG1heF9vZmZfeSA9IG1heCgwLjAsIGV5ZV9yeV9weCAtIHB1cGlsX3JfcHggLSAoMS42ICogcykpCiAgICAgICAgICAgICAgICBvZmZfeCA9IGNs
YW1wKChwb2ludGVyX3ggLSBleWVfY3gpIC8gMjQuMCwgLTEuMCwgMS4wKSAqIG1heF9vZmZfeAogICAgICAgICAgICAgICAgb2ZmX3kgPSBjbGFtcCgocG9p
bnRlcl95IC0gZXllX2N5KSAvIDI4LjAsIC0xLjAsIDEuMCkgKiBtYXhfb2ZmX3kKICAgICAgICAgICAgICAgIG9mZl94ID0gY2xhbXAob2ZmX3ggKyAoZmFj
ZSAqIDAuMiAqIHR1cm5fYWJzICogbWF4X29mZl94KSwgLW1heF9vZmZfeCwgbWF4X29mZl94KQogICAgICAgICAgICAgICAgc2VsZi5jYW52YXMuY3JlYXRl
X292YWwoCiAgICAgICAgICAgICAgICAgICAgZXllX2N4ICsgb2ZmX3ggLSBwdXBpbF9yX3B4LAogICAgICAgICAgICAgICAgICAgIGV5ZV9jeSArIG9mZl95
IC0gcHVwaWxfcl9weCwKICAgICAgICAgICAgICAgICAgICBleWVfY3ggKyBvZmZfeCArIHB1cGlsX3JfcHgsCiAgICAgICAgICAgICAgICAgICAgZXllX2N5
ICsgb2ZmX3kgKyBwdXBpbF9yX3B4LAogICAgICAgICAgICAgICAgICAgIGZpbGw9Y29sb3JzWyJwdXBpbCJdLAogICAgICAgICAgICAgICAgICAgIG91dGxp
bmU9Y29sb3JzWyJwdXBpbCJdLAogICAgICAgICAgICAgICAgKQogICAgICAgICAgICAgICAgaWYgdGludCA8IDEuMDoKICAgICAgICAgICAgICAgICAgICBz
ZWxmLmNhbnZhcy5jcmVhdGVfb3ZhbCgKICAgICAgICAgICAgICAgICAgICAgICAgZXllX2N4IC0gZXllX3J4X3B4LAogICAgICAgICAgICAgICAgICAgICAg
ICBleWVfY3kgLSBleWVfcnlfcHgsCiAgICAgICAgICAgICAgICAgICAgICAgIGV5ZV9jeCArIGV5ZV9yeF9weCwKICAgICAgICAgICAgICAgICAgICAgICAg
ZXllX2N5ICsgZXllX3J5X3B4LAogICAgICAgICAgICAgICAgICAgICAgICBmaWxsPSIiLAogICAgICAgICAgICAgICAgICAgICAgICBvdXRsaW5lPWNvbG9y
c1sidHJpbSJdLAogICAgICAgICAgICAgICAgICAgICAgICB3aWR0aD1tYXgoMSwgaW50KDEgKiBzKSksCiAgICAgICAgICAgICAgICAgICAgICAgIHN0aXBw
bGU9ImdyYXk1MCIsCiAgICAgICAgICAgICAgICAgICAgKQoKICAgICAgICBkcmF3X2V5ZShmYXJfZXllX2NlbnRlclswXSwgZmFyX2V5ZV9jZW50ZXJbMV0s
IGZhcl9leWVfcngsIGZhcl9leWVfcnksIGZhcl9wdXBpbF9yLCB0aW50PTAuODUpCiAgICAgICAgZHJhd19leWUobmVhcl9leWVfY2VudGVyWzBdLCBuZWFy
X2V5ZV9jZW50ZXJbMV0sIG5lYXJfZXllX3J4LCBuZWFyX2V5ZV9yeSwgbmVhcl9wdXBpbF9yLCB0aW50PTEuMCkKCiAgICAgICAgbW91dGhfeSA9IDU4ICsg
Ym9keV9ib2IgKyBoZWFkX2JvYgogICAgICAgIGlmIG1vdmluZyBhbmQgc3BlZWQgPiAxNzA6CiAgICAgICAgICAgIG1vdXRoX3gxLCBtb3V0aF94MiA9IHhy
KDgxICsgaGVhZF9zaGlmdCwgODkgKyBoZWFkX3NoaWZ0KQogICAgICAgICAgICBzZWxmLmNhbnZhcy5jcmVhdGVfb3ZhbChtb3V0aF94MSwgeShtb3V0aF95
IC0gMyksIG1vdXRoX3gyLCB5KG1vdXRoX3kgKyA0KSwgZmlsbD1jb2xvcnNbInRyaW0iXSwgb3V0bGluZT1jb2xvcnNbInRyaW0iXSkKICAgICAgICBlbHNl
OgogICAgICAgICAgICBzZWxmLmNhbnZhcy5jcmVhdGVfbGluZSgKICAgICAgICAgICAgICAgIHgoNzYgKyBoZWFkX3NoaWZ0KSwKICAgICAgICAgICAgICAg
IHkobW91dGhfeSksCiAgICAgICAgICAgICAgICB4KDk0ICsgaGVhZF9zaGlmdCksCiAgICAgICAgICAgICAgICB5KG1vdXRoX3kpLAogICAgICAgICAgICAg
ICAgZmlsbD1jb2xvcnNbInRyaW0iXSwKICAgICAgICAgICAgICAgIHdpZHRoPW1heCgyLCBpbnQoMyAqIHMpKSwKICAgICAgICAgICAgICAgIGNhcHN0eWxl
PXRrLlJPVU5ELAogICAgICAgICAgICApCgogICAgZGVmIF9zZXRfdGhlbWUoc2VsZiwgaW5kZXgpOgogICAgICAgIGlkeCA9IGludChjbGFtcChpbmRleCwg
MCwgbGVuKFRIRU1FUykgLSAxKSkKICAgICAgICBzZWxmLmNmZ1sidGhlbWVfaW5kZXgiXSA9IGlkeAogICAgICAgIHNlbGYuY2ZnWyJjb2xvcnMiXSA9IGRp
Y3QoVEhFTUVTW2lkeF1bImNvbG9ycyJdKQogICAgICAgIHNlbGYuX3NhdmVfY29uZmlnKCkKICAgICAgICBzZWxmLl9yZWZyZXNoX3NldHRpbmdzX2NvbnRy
b2xzKCkKCiAgICBkZWYgX3JhbmRvbWl6ZV9sb29rKHNlbGYpOgogICAgICAgIHNlbGYuX3NldF90aGVtZShyYW5kb20ucmFuZHJhbmdlKGxlbihUSEVNRVMp
KSkKICAgICAgICBzZWxmLmNmZ1siYW50ZW5uYV9tb2RlIl0gPSByYW5kb20ucmFuZHJhbmdlKDMpCiAgICAgICAgc2VsZi5fc2F2ZV9jb25maWcoKQogICAg
ICAgIHNlbGYuX3JlZnJlc2hfc2V0dGluZ3NfY29udHJvbHMoKQoKICAgIGRlZiBfcmVzZXRfZGVmYXVsdHMoc2VsZik6CiAgICAgICAgc2VsZi5jZmcgPSBk
ZWZhdWx0X2NvbmZpZygpCiAgICAgICAgc2VsZi5fYXBwbHlfcnVudGltZV9vcHRpb25zKCkKICAgICAgICBzZWxmLl9yZXNpemVfd2luZG93KCkKICAgICAg
ICBzZWxmLl9zYXZlX2NvbmZpZygpCiAgICAgICAgc2VsZi5fcmVmcmVzaF9zZXR0aW5nc19jb250cm9scygpCgogICAgZGVmIF9hcHBseV9zZXR0aW5nKHNl
bGYsIGtleSwgdmFsdWUsIHNhdmU9VHJ1ZSk6CiAgICAgICAgc2VsZi5jZmdba2V5XSA9IHZhbHVlCiAgICAgICAgc2VsZi5jZmcgPSBzYW5pdGl6ZV9jb25m
aWcoc2VsZi5jZmcpCiAgICAgICAgc2VsZi5fYXBwbHlfcnVudGltZV9vcHRpb25zKCkKICAgICAgICBpZiBrZXkgPT0gInNjYWxlIjoKICAgICAgICAgICAg
c2VsZi5fcmVzaXplX3dpbmRvdygpCiAgICAgICAgaWYgc2F2ZToKICAgICAgICAgICAgc2VsZi5fc2F2ZV9jb25maWcoKQoKICAgIGRlZiBfb3Blbl9zZXR0
aW5ncyhzZWxmLCBfZXZlbnQ9Tm9uZSk6CiAgICAgICAgaWYgc2VsZi5zZXR0aW5nc193aW5kb3cgaXMgbm90IE5vbmUgYW5kIHNlbGYuc2V0dGluZ3Nfd2lu
ZG93LndpbmZvX2V4aXN0cygpOgogICAgICAgICAgICBzZWxmLnNldHRpbmdzX3dpbmRvdy5kZWljb25pZnkoKQogICAgICAgICAgICBzZWxmLnNldHRpbmdz
X3dpbmRvdy5saWZ0KCkKICAgICAgICAgICAgc2VsZi5zZXR0aW5nc193aW5kb3cuZm9jdXNfZm9yY2UoKQogICAgICAgICAgICByZXR1cm4KCiAgICAgICAg
d2luID0gdGsuVG9wbGV2ZWwoc2VsZi5yb290KQogICAgICAgIHdpbi50aXRsZSgiUm9ib3QgUGV0IEN1c3RvbWl6ZXIiKQogICAgICAgIHdpbi5nZW9tZXRy
eSgiNjAweDcwMCIpCiAgICAgICAgd2luLm1pbnNpemUoNTQwLCA2MjApCiAgICAgICAgd2luLnByb3RvY29sKCJXTV9ERUxFVEVfV0lORE9XIiwgc2VsZi5f
Y2xvc2Vfc2V0dGluZ3MpCiAgICAgICAgc2VsZi5zZXR0aW5nc193aW5kb3cgPSB3aW4KCiAgICAgICAgcm9vdF9mcmFtZSA9IHR0ay5GcmFtZSh3aW4sIHBh
ZGRpbmc9MTApCiAgICAgICAgcm9vdF9mcmFtZS5wYWNrKGZpbGw9ImJvdGgiLCBleHBhbmQ9VHJ1ZSkKCiAgICAgICAgbm90ZWJvb2sgPSB0dGsuTm90ZWJv
b2socm9vdF9mcmFtZSkKICAgICAgICBub3RlYm9vay5wYWNrKGZpbGw9ImJvdGgiLCBleHBhbmQ9VHJ1ZSkKCiAgICAgICAgdGFiX2dlbmVyYWwgPSB0dGsu
RnJhbWUobm90ZWJvb2ssIHBhZGRpbmc9MTApCiAgICAgICAgdGFiX21vdGlvbiA9IHR0ay5GcmFtZShub3RlYm9vaywgcGFkZGluZz0xMCkKICAgICAgICB0
YWJfYW5pbSA9IHR0ay5GcmFtZShub3RlYm9vaywgcGFkZGluZz0xMCkKICAgICAgICB0YWJfY29sb3JzID0gdHRrLkZyYW1lKG5vdGVib29rLCBwYWRkaW5n
PTEwKQogICAgICAgIHRhYl9jaGF0ID0gdHRrLkZyYW1lKG5vdGVib29rLCBwYWRkaW5nPTEwKQoKICAgICAgICBub3RlYm9vay5hZGQodGFiX2dlbmVyYWws
IHRleHQ9IkdlbmVyYWwiKQogICAgICAgIG5vdGVib29rLmFkZCh0YWJfbW90aW9uLCB0ZXh0PSJNb3Rpb24iKQogICAgICAgIG5vdGVib29rLmFkZCh0YWJf
YW5pbSwgdGV4dD0iQW5pbWF0aW9uIikKICAgICAgICBub3RlYm9vay5hZGQodGFiX2NvbG9ycywgdGV4dD0iQ29sb3JzIikKICAgICAgICBub3RlYm9vay5h
ZGQodGFiX2NoYXQsIHRleHQ9IkNoYXQiKQoKICAgICAgICBzZWxmLnNldHRpbmdzX3ZhcnMgPSB7fQogICAgICAgIHNlbGYuY29sb3Jfc3dhdGNoZXMgPSB7
fQ0KCiAgICAgICAgdHRrLkxhYmVsKHRhYl9nZW5lcmFsLCB0ZXh0PSJUZXJtaW5hbCBNZW51IiwgZm9udD0oIlNlZ29lIFVJIiwgMTAsICJib2xkIikpLnBh
Y2soYW5jaG9yPSJ3IiwgcGFkeT0oMCwgNikpCiAgICAgICAgdHRrLkxhYmVsKHRhYl9nZW5lcmFsLCB0ZXh0PSJVc2UgdGVybWluYWwgbWVudTogMSkgVG9n
Z2xlICAyKSBPcGVuIEN1c3RvbWl6ZXIgIDMpIFF1aXQiKS5wYWNrKGFuY2hvcj0idyIsIHBhZHk9KDAsIDEwKSkKCiAgICAgICAgdGhlbWVfbmFtZXMgPSBb
dFsibmFtZSJdIGZvciB0IGluIFRIRU1FU10KICAgICAgICB0aGVtZV9yb3cgPSB0dGsuRnJhbWUodGFiX2dlbmVyYWwpCiAgICAgICAgdGhlbWVfcm93LnBh
Y2soZmlsbD0ieCIsIHBhZHk9NCkKICAgICAgICB0dGsuTGFiZWwodGhlbWVfcm93LCB0ZXh0PSJUaGVtZSIsIHdpZHRoPTE2KS5wYWNrKHNpZGU9ImxlZnQi
KQogICAgICAgIHRoZW1lX3ZhciA9IHRrLlN0cmluZ1Zhcih2YWx1ZT10aGVtZV9uYW1lc1tpbnQoc2VsZi5jZmdbInRoZW1lX2luZGV4Il0pXSkKICAgICAg
ICBzZWxmLnNldHRpbmdzX3ZhcnNbInRoZW1lX25hbWUiXSA9IHRoZW1lX3ZhcgogICAgICAgIHRoZW1lX2NvbWJvID0gdHRrLkNvbWJvYm94KHRoZW1lX3Jv
dywgdmFsdWVzPXRoZW1lX25hbWVzLCB0ZXh0dmFyaWFibGU9dGhlbWVfdmFyLCBzdGF0ZT0icmVhZG9ubHkiKQogICAgICAgIHRoZW1lX2NvbWJvLnBhY2so
c2lkZT0ibGVmdCIsIGZpbGw9IngiLCBleHBhbmQ9VHJ1ZSkKCiAgICAgICAgZGVmIGFwcGx5X3RoZW1lKF9ldmVudD1Ob25lKToKICAgICAgICAgICAgbmFt
ZSA9IHRoZW1lX3Zhci5nZXQoKQogICAgICAgICAgICBpZiBuYW1lIGluIHRoZW1lX25hbWVzOgogICAgICAgICAgICAgICAgc2VsZi5fc2V0X3RoZW1lKHRo
ZW1lX25hbWVzLmluZGV4KG5hbWUpKQoKICAgICAgICB0aGVtZV9jb21iby5iaW5kKCI8PENvbWJvYm94U2VsZWN0ZWQ+PiIsIGFwcGx5X3RoZW1lKQoKICAg
ICAgICBhbnRlbm5hX21vZGVzID0gWyJTaW5nbGUiLCAiRHVhbCIsICJEaXNoIl0KICAgICAgICBhbnRlbm5hX3JvdyA9IHR0ay5GcmFtZSh0YWJfZ2VuZXJh
bCkKICAgICAgICBhbnRlbm5hX3Jvdy5wYWNrKGZpbGw9IngiLCBwYWR5PTQpCiAgICAgICAgdHRrLkxhYmVsKGFudGVubmFfcm93LCB0ZXh0PSJBbnRlbm5h
Iiwgd2lkdGg9MTYpLnBhY2soc2lkZT0ibGVmdCIpCiAgICAgICAgYW50ZW5uYV92YXIgPSB0ay5TdHJpbmdWYXIodmFsdWU9YW50ZW5uYV9tb2Rlc1tpbnQo
c2VsZi5jZmdbImFudGVubmFfbW9kZSJdKV0pCiAgICAgICAgc2VsZi5zZXR0aW5nc192YXJzWyJhbnRlbm5hX25hbWUiXSA9IGFudGVubmFfdmFyCiAgICAg
ICAgYW50ZW5uYV9jb21ibyA9IHR0ay5Db21ib2JveChhbnRlbm5hX3JvdywgdmFsdWVzPWFudGVubmFfbW9kZXMsIHRleHR2YXJpYWJsZT1hbnRlbm5hX3Zh
ciwgc3RhdGU9InJlYWRvbmx5IikKICAgICAgICBhbnRlbm5hX2NvbWJvLnBhY2soc2lkZT0ibGVmdCIsIGZpbGw9IngiLCBleHBhbmQ9VHJ1ZSkKCiAgICAg
ICAgZGVmIGFwcGx5X2FudGVubmEoX2V2ZW50PU5vbmUpOgogICAgICAgICAgICBuYW1lID0gYW50ZW5uYV92YXIuZ2V0KCkKICAgICAgICAgICAgaWYgbmFt
ZSBpbiBhbnRlbm5hX21vZGVzOgogICAgICAgICAgICAgICAgc2VsZi5fYXBwbHlfc2V0dGluZygiYW50ZW5uYV9tb2RlIiwgYW50ZW5uYV9tb2Rlcy5pbmRl
eChuYW1lKSkKCiAgICAgICAgYW50ZW5uYV9jb21iby5iaW5kKCI8PENvbWJvYm94U2VsZWN0ZWQ+PiIsIGFwcGx5X2FudGVubmEpCgogICAgICAgIHRvcG1v
c3RfdmFyID0gdGsuQm9vbGVhblZhcih2YWx1ZT1ib29sKHNlbGYuY2ZnWyJ0b3Btb3N0Il0pKQogICAgICAgIHNlbGYuc2V0dGluZ3NfdmFyc1sidG9wbW9z
dCJdID0gdG9wbW9zdF92YXIKICAgICAgICB0dGsuQ2hlY2tidXR0b24oCiAgICAgICAgICAgIHRhYl9nZW5lcmFsLAogICAgICAgICAgICB0ZXh0PSJLZWVw
IHBldCBvbiB0b3AiLAogICAgICAgICAgICB2YXJpYWJsZT10b3Btb3N0X3ZhciwKICAgICAgICAgICAgY29tbWFuZD1sYW1iZGE6IHNlbGYuX2FwcGx5X3Nl
dHRpbmcoInRvcG1vc3QiLCBib29sKHRvcG1vc3RfdmFyLmdldCgpKSksCiAgICAgICAgKS5wYWNrKGFuY2hvcj0idyIsIHBhZHk9NCkKCiAgICAgICAgc2hh
ZG93X3ZhciA9IHRrLkJvb2xlYW5WYXIodmFsdWU9Ym9vbChzZWxmLmNmZ1sic2hvd19zaGFkb3ciXSkpCiAgICAgICAgc2VsZi5zZXR0aW5nc192YXJzWyJz
aG93X3NoYWRvdyJdID0gc2hhZG93X3ZhcgogICAgICAgIHR0ay5DaGVja2J1dHRvbigKICAgICAgICAgICAgdGFiX2dlbmVyYWwsCiAgICAgICAgICAgIHRl
eHQ9IlNob3cgZ3JvdW5kIHNoYWRvdyIsCiAgICAgICAgICAgIHZhcmlhYmxlPXNoYWRvd192YXIsCiAgICAgICAgICAgIGNvbW1hbmQ9bGFtYmRhOiBzZWxm
Ll9hcHBseV9zZXR0aW5nKCJzaG93X3NoYWRvdyIsIGJvb2woc2hhZG93X3Zhci5nZXQoKSkpLAogICAgICAgICkucGFjayhhbmNob3I9InciLCBwYWR5PTQp
CgogICAgICAgIGJ0bl9yb3cgPSB0dGsuRnJhbWUodGFiX2dlbmVyYWwpCiAgICAgICAgYnRuX3Jvdy5wYWNrKGZpbGw9IngiLCBwYWR5PSgxMiwgNikpCiAg
ICAgICAgdHRrLkJ1dHRvbihidG5fcm93LCB0ZXh0PSJSYW5kb21pemUgTG9vayIsIGNvbW1hbmQ9c2VsZi5fcmFuZG9taXplX2xvb2spLnBhY2soc2lkZT0i
bGVmdCIsIHBhZHg9KDAsIDgpKQogICAgICAgIHR0ay5CdXR0b24oYnRuX3JvdywgdGV4dD0iUmVzZXQgRGVmYXVsdHMiLCBjb21tYW5kPXNlbGYuX3Jlc2V0
X2RlZmF1bHRzKS5wYWNrKHNpZGU9ImxlZnQiLCBwYWR4PSgwLCA4KSkKICAgICAgICB0dGsuQnV0dG9uKGJ0bl9yb3csIHRleHQ9IkhpZGUvU2hvdyBQZXQi
LCBjb21tYW5kPXNlbGYuX3RvZ2dsZV92aXNpYmlsaXR5KS5wYWNrKHNpZGU9ImxlZnQiKQoKICAgICAgICBkZWYgYWRkX3NsaWRlcihwYXJlbnQsIGxhYmVs
LCBrZXksIGxvLCBoaSwgcmVzb2x1dGlvbj0wLjEsIGFzX2ludD1GYWxzZSk6CiAgICAgICAgICAgIHJvdyA9IHR0ay5GcmFtZShwYXJlbnQpCiAgICAgICAg
ICAgIHJvdy5wYWNrKGZpbGw9IngiLCBwYWR5PTUpCgogICAgICAgICAgICBoZWFkID0gdHRrLkZyYW1lKHJvdykKICAgICAgICAgICAgaGVhZC5wYWNrKGZp
bGw9IngiKQogICAgICAgICAgICB0dGsuTGFiZWwoaGVhZCwgdGV4dD1sYWJlbCkucGFjayhzaWRlPSJsZWZ0IikKICAgICAgICAgICAgdmFsdWVfbGFiZWwg
PSB0dGsuTGFiZWwoaGVhZCwgd2lkdGg9MTAsIGFuY2hvcj0iZSIpCiAgICAgICAgICAgIHZhbHVlX2xhYmVsLnBhY2soc2lkZT0icmlnaHQiKQoKICAgICAg
ICAgICAgdmFyID0gdGsuRG91YmxlVmFyKHZhbHVlPWZsb2F0KHNlbGYuY2ZnW2tleV0pKQogICAgICAgICAgICBzZWxmLnNldHRpbmdzX3ZhcnNba2V5XSA9
IHZhcgoKICAgICAgICAgICAgZGVmIGFwcGx5X3ZhbHVlKF9hcmc9Tm9uZSk6CiAgICAgICAgICAgICAgICB2YWx1ZSA9IHZhci5nZXQoKQogICAgICAgICAg
ICAgICAgaWYgYXNfaW50OgogICAgICAgICAgICAgICAgICAgIHZhbHVlID0gaW50KHJvdW5kKHZhbHVlKSkKICAgICAgICAgICAgICAgIHNlbGYuX2FwcGx5
X3NldHRpbmcoa2V5LCB2YWx1ZSkKCiAgICAgICAgICAgICAgICB0ZXh0X3ZhbHVlID0gZiJ7aW50KHZhbHVlKX0iIGlmIGFzX2ludCBlbHNlIGYie2Zsb2F0
KHZhbHVlKTouMmZ9IgogICAgICAgICAgICAgICAgdmFsdWVfbGFiZWwuY29uZmlnKHRleHQ9dGV4dF92YWx1ZSkKCiAgICAgICAgICAgICAgICBpZiBrZXkg
aW4gKCJibGlua19taW4iLCAiYmxpbmtfbWF4Iik6CiAgICAgICAgICAgICAgICAgICAgc2VsZi5jZmcgPSBzYW5pdGl6ZV9jb25maWcoc2VsZi5jZmcpCiAg
ICAgICAgICAgICAgICAgICAgc2VsZi5zZXR0aW5nc192YXJzWyJibGlua19taW4iXS5zZXQoZmxvYXQoc2VsZi5jZmdbImJsaW5rX21pbiJdKSkKICAgICAg
ICAgICAgICAgICAgICBzZWxmLnNldHRpbmdzX3ZhcnNbImJsaW5rX21heCJdLnNldChmbG9hdChzZWxmLmNmZ1siYmxpbmtfbWF4Il0pKQogICAgICAgICAg
ICAgICAgICAgIHNlbGYuX3NhdmVfY29uZmlnKCkKCiAgICAgICAgICAgIHZhbHVlX2xhYmVsLmNvbmZpZyh0ZXh0PWYie2Zsb2F0KHZhci5nZXQoKSk6LjJm
fSIgaWYgbm90IGFzX2ludCBlbHNlIGYie2ludCh2YXIuZ2V0KCkpfSIpCgogICAgICAgICAgICBzY2FsZSA9IHRrLlNjYWxlKAogICAgICAgICAgICAgICAg
cm93LAogICAgICAgICAgICAgICAgZnJvbV89bG8sCiAgICAgICAgICAgICAgICB0bz1oaSwKICAgICAgICAgICAgICAgIHJlc29sdXRpb249cmVzb2x1dGlv
biwKICAgICAgICAgICAgICAgIG9yaWVudD0iaG9yaXpvbnRhbCIsCiAgICAgICAgICAgICAgICB2YXJpYWJsZT12YXIsCiAgICAgICAgICAgICAgICBzaG93
dmFsdWU9RmFsc2UsCiAgICAgICAgICAgICAgICBjb21tYW5kPWFwcGx5X3ZhbHVlLAogICAgICAgICAgICApCiAgICAgICAgICAgIHNjYWxlLnBhY2soZmls
bD0ieCIpCgogICAgICAgIGFkZF9zbGlkZXIodGFiX21vdGlvbiwgIlNpemUiLCAic2NhbGUiLCAwLjI4LCAyLjIsIDAuMDEpCiAgICAgICAgYWRkX3NsaWRl
cih0YWJfbW90aW9uLCAiTWF4IFNwZWVkIiwgIm1heF9zcGVlZCIsIDEyMCwgMTMwMCwgMSwgYXNfaW50PVRydWUpCiAgICAgICAgYWRkX3NsaWRlcih0YWJf
bW90aW9uLCAiRm9sbG93IE9mZnNldCBYIiwgImZvbGxvd19vZmZzZXRfeCIsIC0yNTAsIDI1MCwgMSwgYXNfaW50PVRydWUpCiAgICAgICAgYWRkX3NsaWRl
cih0YWJfbW90aW9uLCAiRm9sbG93IE9mZnNldCBZIiwgImZvbGxvd19vZmZzZXRfeSIsIC0yMDAsIDI1MCwgMSwgYXNfaW50PVRydWUpCiAgICAgICAgYWRk
X3NsaWRlcih0YWJfbW90aW9uLCAiU3RvcCBSYWRpdXMiLCAic3RvcF9yYWRpdXMiLCAyLCAxMjAsIDAuNSkKICAgICAgICBhZGRfc2xpZGVyKHRhYl9tb3Rp
b24sICJBY2NlbGVyYXRpb24iLCAiYWNjZWxlcmF0aW9uIiwgMiwgMjUsIDAuMSkKICAgICAgICBhZGRfc2xpZGVyKHRhYl9tb3Rpb24sICJEYW1waW5nIiwg
ImRhbXBpbmciLCAyLCAyNSwgMC4xKQogICAgICAgIGFkZF9zbGlkZXIodGFiX21vdGlvbiwgIk9wYWNpdHkiLCAib3BhY2l0eSIsIDAuMzUsIDEuMCwgMC4w
MSkKCiAgICAgICAgYWRkX3NsaWRlcih0YWJfYW5pbSwgIklkbGUgQm9iIiwgImlkbGVfYm9iX2FtcCIsIDAsIDYsIDAuMSkKICAgICAgICBhZGRfc2xpZGVy
KHRhYl9hbmltLCAiV2FsayBCb2IiLCAid2Fsa19ib2JfYW1wIiwgMCwgOCwgMC4xKQogICAgICAgIGFkZF9zbGlkZXIodGFiX2FuaW0sICJIZWFkIEJvYiIs
ICJoZWFkX2JvYl9hbXAiLCAwLCAxMCwgMC4xKQogICAgICAgIGFkZF9zbGlkZXIodGFiX2FuaW0sICJMZWcgTGlmdCIsICJsZWdfbGlmdF9hbXAiLCAwLCAy
MCwgMC4xKQogICAgICAgIGFkZF9zbGlkZXIodGFiX2FuaW0sICJBcm0gU3dpbmciLCAiYXJtX3N3aW5nX2FtcCIsIDAsIDIwLCAwLjEpCiAgICAgICAgYWRk
X3NsaWRlcih0YWJfYW5pbSwgIkV5ZSBTaXplIiwgImV5ZV9zY2FsZSIsIDAuNSwgMS44LCAwLjAxKQogICAgICAgIGFkZF9zbGlkZXIodGFiX2FuaW0sICJQ
dXBpbCBTaXplIiwgInB1cGlsX3NjYWxlIiwgMC40LCAyLjIsIDAuMDEpCiAgICAgICAgYWRkX3NsaWRlcih0YWJfYW5pbSwgIkJsaW5rIE1pbiIsICJibGlu
a19taW4iLCAwLjIsIDgsIDAuMDUpCiAgICAgICAgYWRkX3NsaWRlcih0YWJfYW5pbSwgIkJsaW5rIE1heCIsICJibGlua19tYXgiLCAwLjMsIDEyLCAwLjA1
KQoKICAgICAgICB0dGsuTGFiZWwodGFiX2NvbG9ycywgdGV4dD0iUGljayByb2JvdCBjb2xvcnMiLCBmb250PSgiU2Vnb2UgVUkiLCAxMCwgImJvbGQiKSku
cGFjayhhbmNob3I9InciLCBwYWR5PSgwLCA4KSkKICAgICAgICBmb3Iga2V5IGluIFsiYm9keSIsICJ0cmltIiwgInBhbmVsIiwgImV5ZSIsICJwdXBpbCIs
ICJhY2NlbnQiLCAic2hhZG93Il06CiAgICAgICAgICAgIHJvdyA9IHR0ay5GcmFtZSh0YWJfY29sb3JzKQogICAgICAgICAgICByb3cucGFjayhmaWxsPSJ4
IiwgcGFkeT00KQogICAgICAgICAgICB0dGsuTGFiZWwocm93LCB0ZXh0PWtleS5jYXBpdGFsaXplKCksIHdpZHRoPTEyKS5wYWNrKHNpZGU9ImxlZnQiKQoK
ICAgICAgICAgICAgc3dhdGNoID0gdGsuTGFiZWwocm93LCB3aWR0aD01LCBiZz1zZWxmLmNmZ1siY29sb3JzIl1ba2V5XSwgcmVsaWVmPSJzdW5rZW4iLCBi
ZD0xKQogICAgICAgICAgICBzd2F0Y2gucGFjayhzaWRlPSJsZWZ0IiwgcGFkeD0oMCwgOCkpCiAgICAgICAgICAgIHNlbGYuY29sb3Jfc3dhdGNoZXNba2V5
XSA9IHN3YXRjaAoKICAgICAgICAgICAgZGVmIG1ha2VfcGlja2VyKGNvbG9yX2tleSk6CiAgICAgICAgICAgICAgICBkZWYgcGljaygpOgogICAgICAgICAg
ICAgICAgICAgIHBpY2tlZCA9IGNvbG9yY2hvb3Nlci5hc2tjb2xvcihzZWxmLmNmZ1siY29sb3JzIl1bY29sb3Jfa2V5XSwgcGFyZW50PXdpbilbMV0KICAg
ICAgICAgICAgICAgICAgICBpZiBwaWNrZWQ6CiAgICAgICAgICAgICAgICAgICAgICAgIHNlbGYuY2ZnWyJjb2xvcnMiXVtjb2xvcl9rZXldID0gcGlja2Vk
CiAgICAgICAgICAgICAgICAgICAgICAgIHNlbGYuY29sb3Jfc3dhdGNoZXNbY29sb3Jfa2V5XS5jb25maWcoYmc9cGlja2VkKQogICAgICAgICAgICAgICAg
ICAgICAgICBzZWxmLl9zYXZlX2NvbmZpZygpCgogICAgICAgICAgICAgICAgcmV0dXJuIHBpY2sKCiAgICAgICAgICAgIHR0ay5CdXR0b24ocm93LCB0ZXh0
PSJDaG9vc2UuLi4iLCBjb21tYW5kPW1ha2VfcGlja2VyKGtleSkpLnBhY2soc2lkZT0ibGVmdCIpCgogICAgICAgIGNvbG9yX2J0biA9IHR0ay5GcmFtZSh0
YWJfY29sb3JzKQogICAgICAgIGNvbG9yX2J0bi5wYWNrKGZpbGw9IngiLCBwYWR5PSgxMCwgNCkpCgogICAgICAgIGRlZiByZXNldF90aGVtZV9jb2xvcnMo
KToKICAgICAgICAgICAgaWR4ID0gaW50KHNlbGYuY2ZnWyJ0aGVtZV9pbmRleCJdKQogICAgICAgICAgICBzZWxmLmNmZ1siY29sb3JzIl0gPSBkaWN0KFRI
RU1FU1tpZHhdWyJjb2xvcnMiXSkKICAgICAgICAgICAgc2VsZi5fc2F2ZV9jb25maWcoKQogICAgICAgICAgICBzZWxmLl9yZWZyZXNoX3NldHRpbmdzX2Nv
bnRyb2xzKCkKCiAgICAgICAgdHRrLkJ1dHRvbihjb2xvcl9idG4sIHRleHQ9IlJlc2V0IENvbG9ycyBUbyBUaGVtZSIsIGNvbW1hbmQ9cmVzZXRfdGhlbWVf
Y29sb3JzKS5wYWNrKHNpZGU9ImxlZnQiKQoKICAgICAgICAjIENoYXQgdGFiIChPbGxhbWEpCiAgICAgICAgdHRrLkxhYmVsKHRhYl9jaGF0LCB0ZXh0PSJU
YWxrIHRvIEJ5dGUiLCBmb250PSgiU2Vnb2UgVUkiLCAxMCwgImJvbGQiKSkucGFjayhhbmNob3I9InciKQogICAgICAgIHR0ay5MYWJlbCh0YWJfY2hhdCwg
dGV4dD1mIk1vZGVsOiB7T0xMQU1BX01PREVMfSIpLnBhY2soYW5jaG9yPSJ3IiwgcGFkeT0oMCwgNCkpCiAgICAgICAgdHRrLkxhYmVsKHRhYl9jaGF0LCB0
ZXh0PWYiRW5kcG9pbnQ6IHtPTExBTUFfQ0hBVF9VUkx9IikucGFjayhhbmNob3I9InciLCBwYWR5PSgwLCA4KSkKCiAgICAgICAgY2hhdF9sb2cgPSB0ay5U
ZXh0KHRhYl9jaGF0LCBoZWlnaHQ9MTYsIHdyYXA9IndvcmQiLCBzdGF0ZT0iZGlzYWJsZWQiKQogICAgICAgIGNoYXRfbG9nLnBhY2soZmlsbD0iYm90aCIs
IGV4cGFuZD1UcnVlKQoKICAgICAgICBmb3IgbGluZSBpbiBzZWxmLmNoYXRfaGlzdG9yeToKICAgICAgICAgICAgY2hhdF9sb2cuY29uZmlndXJlKHN0YXRl
PSJub3JtYWwiKQogICAgICAgICAgICBjaGF0X2xvZy5pbnNlcnQoImVuZCIsIGxpbmUgKyAiXG4iKQogICAgICAgICAgICBjaGF0X2xvZy5jb25maWd1cmUo
c3RhdGU9ImRpc2FibGVkIikKICAgICAgICBjaGF0X2xvZy5zZWUoImVuZCIpCgogICAgICAgIGVudHJ5X3JvdyA9IHR0ay5GcmFtZSh0YWJfY2hhdCkKICAg
ICAgICBlbnRyeV9yb3cucGFjayhmaWxsPSJ4IiwgcGFkeT0oOCwgNCkpCiAgICAgICAgY2hhdF9lbnRyeSA9IHR0ay5FbnRyeShlbnRyeV9yb3cpCiAgICAg
ICAgY2hhdF9lbnRyeS5wYWNrKHNpZGU9ImxlZnQiLCBmaWxsPSJ4IiwgZXhwYW5kPVRydWUpCiAgICAgICAgc2VuZF9idG4gPSB0dGsuQnV0dG9uKGVudHJ5
X3JvdywgdGV4dD0iU2VuZCIsIGNvbW1hbmQ9c2VsZi5fc3VibWl0X2NoYXQpCiAgICAgICAgc2VuZF9idG4ucGFjayhzaWRlPSJsZWZ0IiwgcGFkeD0oOCwg
MCkpCiAgICAgICAgY2hhdF9lbnRyeS5iaW5kKCI8UmV0dXJuPiIsIHNlbGYuX3N1Ym1pdF9jaGF0KQoKICAgICAgICBjaGF0X3N0YXR1cyA9IHRrLlN0cmlu
Z1Zhcih2YWx1ZT0iUmVhZHkiKQogICAgICAgIHR0ay5MYWJlbCh0YWJfY2hhdCwgdGV4dHZhcmlhYmxlPWNoYXRfc3RhdHVzKS5wYWNrKGFuY2hvcj0idyIs
IHBhZHk9KDIsIDYpKQoKICAgICAgICBzcGVha192YXIgPSB0ay5Cb29sZWFuVmFyKHZhbHVlPWJvb2woc2VsZi5jZmdbInNwZWFrX3JlcGxpZXMiXSkpCiAg
ICAgICAgc2VsZi5zZXR0aW5nc192YXJzWyJzcGVha19yZXBsaWVzIl0gPSBzcGVha192YXIKICAgICAgICB0dGsuQ2hlY2tidXR0b24oCiAgICAgICAgICAg
IHRhYl9jaGF0LAogICAgICAgICAgICB0ZXh0PSJTcGVhayByb2JvdCByZXBsaWVzIiwKICAgICAgICAgICAgdmFyaWFibGU9c3BlYWtfdmFyLAogICAgICAg
ICAgICBjb21tYW5kPWxhbWJkYTogc2VsZi5fYXBwbHlfc2V0dGluZygic3BlYWtfcmVwbGllcyIsIGJvb2woc3BlYWtfdmFyLmdldCgpKSksCiAgICAgICAg
KS5wYWNrKGFuY2hvcj0idyIpCgogICAgICAgIHZvaWNlX3JvdyA9IHR0ay5GcmFtZSh0YWJfY2hhdCkKICAgICAgICB2b2ljZV9yb3cucGFjayhmaWxsPSJ4
IiwgcGFkeT0oNiwgMCkpCiAgICAgICAgdHRrLkxhYmVsKHZvaWNlX3JvdywgdGV4dD0iVm9pY2UgUmF0ZSIsIHdpZHRoPTE2KS5wYWNrKHNpZGU9ImxlZnQi
KQogICAgICAgIHZvaWNlX3JhdGVfdmFyID0gdGsuRG91YmxlVmFyKHZhbHVlPWZsb2F0KHNlbGYuY2ZnWyJ2b2ljZV9yYXRlIl0pKQogICAgICAgIHNlbGYu
c2V0dGluZ3NfdmFyc1sidm9pY2VfcmF0ZSJdID0gdm9pY2VfcmF0ZV92YXIKICAgICAgICB2b2ljZV92YWx1ZSA9IHR0ay5MYWJlbCh2b2ljZV9yb3csIHdp
ZHRoPTYsIGFuY2hvcj0iZSIsIHRleHQ9c3RyKGludChzZWxmLmNmZ1sidm9pY2VfcmF0ZSJdKSkpCiAgICAgICAgdm9pY2VfdmFsdWUucGFjayhzaWRlPSJy
aWdodCIpCgogICAgICAgIGRlZiBhcHBseV92b2ljZV9yYXRlKF9hcmc9Tm9uZSk6CiAgICAgICAgICAgIHJhdGUgPSBpbnQocm91bmQodm9pY2VfcmF0ZV92
YXIuZ2V0KCkpKQogICAgICAgICAgICBzZWxmLl9hcHBseV9zZXR0aW5nKCJ2b2ljZV9yYXRlIiwgcmF0ZSkKICAgICAgICAgICAgdm9pY2VfdmFsdWUuY29u
ZmlnKHRleHQ9c3RyKGludChzZWxmLmNmZ1sidm9pY2VfcmF0ZSJdKSkpCgogICAgICAgIHZvaWNlX3NjYWxlID0gdGsuU2NhbGUoCiAgICAgICAgICAgIHRh
Yl9jaGF0LAogICAgICAgICAgICBmcm9tXz0tOCwKICAgICAgICAgICAgdG89OCwKICAgICAgICAgICAgcmVzb2x1dGlvbj0xLAogICAgICAgICAgICBvcmll
bnQ9Imhvcml6b250YWwiLAogICAgICAgICAgICB2YXJpYWJsZT12b2ljZV9yYXRlX3ZhciwKICAgICAgICAgICAgc2hvd3ZhbHVlPUZhbHNlLAogICAgICAg
ICAgICBjb21tYW5kPWFwcGx5X3ZvaWNlX3JhdGUsCiAgICAgICAgKQogICAgICAgIHZvaWNlX3NjYWxlLnBhY2soZmlsbD0ieCIpCgogICAgICAgIHNlbGYu
Y2hhdF93aWRnZXRzID0gewogICAgICAgICAgICAibG9nIjogY2hhdF9sb2csCiAgICAgICAgICAgICJlbnRyeSI6IGNoYXRfZW50cnksCiAgICAgICAgICAg
ICJzZW5kIjogc2VuZF9idG4sCiAgICAgICAgICAgICJzdGF0dXMiOiBjaGF0X3N0YXR1cywKICAgICAgICB9CiAgICAgICAgc2VsZi5fc2V0X2NoYXRfYnVz
eShzZWxmLmNoYXRfYnVzeSkKICAgICAgICBzZWxmLl9zZXRfY2hhdF9zdGF0dXMoZiJTdHJlYW1pbmcgd2l0aCB7T0xMQU1BX01PREVMfS4uLiIgaWYgc2Vs
Zi5jaGF0X2J1c3kgZWxzZSAiUmVhZHkiKQogICAgICAgIGlmIG5vdCBzZWxmLmNoYXRfYnVzeToKICAgICAgICAgICAgY2hhdF9lbnRyeS5mb2N1c19zZXQo
KQoKICAgICAgICBmb290ZXIgPSB0dGsuRnJhbWUocm9vdF9mcmFtZSkKICAgICAgICBmb290ZXIucGFjayhmaWxsPSJ4IiwgcGFkeT0oOCwgMCkpCiAgICAg
ICAgdHRrLkxhYmVsKAogICAgICAgICAgICBmb290ZXIsCiAgICAgICAgICAgIHRleHQ9IkNoYXJhY3RlciB0ZXh0IG92ZXJsYXkgcmVtb3ZlZC4gQ3VzdG9t
aXplIGV2ZXJ5dGhpbmcgZnJvbSB0aGlzIEdVSSB3aW5kb3cuIiwKICAgICAgICAgICAgZm9yZWdyb3VuZD0iIzJmM2I1MiIsCiAgICAgICAgKS5wYWNrKGFu
Y2hvcj0idyIpCgogICAgZGVmIF9jbG9zZV9zZXR0aW5ncyhzZWxmKToKICAgICAgICBpZiBzZWxmLnNldHRpbmdzX3dpbmRvdyBpcyBub3QgTm9uZSBhbmQg
c2VsZi5zZXR0aW5nc193aW5kb3cud2luZm9fZXhpc3RzKCk6CiAgICAgICAgICAgIHNlbGYuc2V0dGluZ3Nfd2luZG93LmRlc3Ryb3koKQogICAgICAgIHNl
bGYuc2V0dGluZ3Nfd2luZG93ID0gTm9uZQogICAgICAgIHNlbGYuc2V0dGluZ3NfdmFycyA9IHt9CiAgICAgICAgc2VsZi5jb2xvcl9zd2F0Y2hlcyA9IHt9
CiAgICAgICAgc2VsZi5jaGF0X3dpZGdldHMgPSB7fQoKICAgIGRlZiBfcmVmcmVzaF9zZXR0aW5nc19jb250cm9scyhzZWxmKToKICAgICAgICBpZiBzZWxm
LnNldHRpbmdzX3dpbmRvdyBpcyBOb25lIG9yIG5vdCBzZWxmLnNldHRpbmdzX3dpbmRvdy53aW5mb19leGlzdHMoKToKICAgICAgICAgICAgcmV0dXJuCgog
ICAgICAgIHRoZW1lX25hbWVzID0gW3RbIm5hbWUiXSBmb3IgdCBpbiBUSEVNRVNdCiAgICAgICAgYW50ZW5uYV9uYW1lcyA9IFsiU2luZ2xlIiwgIkR1YWwi
LCAiRGlzaCJdCgogICAgICAgIGlmICJ0aGVtZV9uYW1lIiBpbiBzZWxmLnNldHRpbmdzX3ZhcnM6CiAgICAgICAgICAgIHNlbGYuc2V0dGluZ3NfdmFyc1si
dGhlbWVfbmFtZSJdLnNldCh0aGVtZV9uYW1lc1tpbnQoc2VsZi5jZmdbInRoZW1lX2luZGV4Il0pXSkKICAgICAgICBpZiAiYW50ZW5uYV9uYW1lIiBpbiBz
ZWxmLnNldHRpbmdzX3ZhcnM6CiAgICAgICAgICAgIHNlbGYuc2V0dGluZ3NfdmFyc1siYW50ZW5uYV9uYW1lIl0uc2V0KGFudGVubmFfbmFtZXNbaW50KHNl
bGYuY2ZnWyJhbnRlbm5hX21vZGUiXSldKQoKICAgICAgICBmb3Iga2V5LCB2YXIgaW4gc2VsZi5zZXR0aW5nc192YXJzLml0ZW1zKCk6CiAgICAgICAgICAg
IGlmIGtleSBpbiAoInRoZW1lX25hbWUiLCAiYW50ZW5uYV9uYW1lIik6CiAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICBpZiBrZXkgaW4g
c2VsZi5jZmc6CiAgICAgICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAgICAgdmFyLnNldChzZWxmLmNmZ1trZXldKQogICAgICAgICAgICAgICAg
ZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgICAgICAgICBwYXNzCgogICAgICAgIGZvciBrZXksIHN3YXRjaCBpbiBzZWxmLmNvbG9yX3N3YXRjaGVz
Lml0ZW1zKCk6CiAgICAgICAgICAgIGlmIGtleSBpbiBzZWxmLmNmZ1siY29sb3JzIl06CiAgICAgICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAg
ICAgc3dhdGNoLmNvbmZpZyhiZz1zZWxmLmNmZ1siY29sb3JzIl1ba2V5XSkKICAgICAgICAgICAgICAgIGV4Y2VwdCB0ay5UY2xFcnJvcjoKICAgICAgICAg
ICAgICAgICAgICBwYXNzCgogICAgZGVmIF9kcmFpbl9jaGF0X3F1ZXVlKHNlbGYpOgogICAgICAgIHdoaWxlIFRydWU6CiAgICAgICAgICAgIHRyeToKICAg
ICAgICAgICAgICAgIGtpbmQsIHBheWxvYWQgPSBzZWxmLmNoYXRfcXVldWUuZ2V0X25vd2FpdCgpCiAgICAgICAgICAgIGV4Y2VwdCBxdWV1ZS5FbXB0eToK
ICAgICAgICAgICAgICAgIGJyZWFrCgogICAgICAgICAgICBpZiBraW5kID09ICJzdHJlYW1fc3RhcnQiOgogICAgICAgICAgICAgICAgc2VsZi5fc3RhcnRf
YXNzaXN0YW50X3N0cmVhbSgpCiAgICAgICAgICAgICAgICBzZWxmLl9zZXRfY2hhdF9zdGF0dXMoZiJTdHJlYW1pbmcgd2l0aCB7T0xMQU1BX01PREVMfS4u
LiIpCiAgICAgICAgICAgIGVsaWYga2luZCA9PSAic3RyZWFtX2RlbHRhIjoKICAgICAgICAgICAgICAgIHNlbGYuX2FwcGVuZF9hc3Npc3RhbnRfc3RyZWFt
KHBheWxvYWQgb3IgIiIpCiAgICAgICAgICAgIGVsaWYga2luZCA9PSAic3RyZWFtX2VuZCI6CiAgICAgICAgICAgICAgICBzZWxmLl9maW5pc2hfYXNzaXN0
YW50X3N0cmVhbSgpCiAgICAgICAgICAgICAgICBzZWxmLl9zZXRfY2hhdF9idXN5KEZhbHNlKQogICAgICAgICAgICAgICAgc2VsZi5fc2V0X2NoYXRfc3Rh
dHVzKCJSZWFkeSIpCiAgICAgICAgICAgIGVsaWYga2luZCA9PSAic3RyZWFtX2Vycm9yIjoKICAgICAgICAgICAgICAgIHNlbGYuX2ZpbmlzaF9hc3Npc3Rh
bnRfc3RyZWFtKCkKICAgICAgICAgICAgICAgIHNlbGYuX3NldF9jaGF0X2J1c3koRmFsc2UpCiAgICAgICAgICAgICAgICBzZWxmLl9hcHBlbmRfY2hhdF9s
aW5lKCJTeXN0ZW0iLCBwYXlsb2FkKQogICAgICAgICAgICAgICAgc2VsZi5fc2V0X2NoYXRfc3RhdHVzKCJFcnJvciIpCgogICAgZGVmIF9kcmFpbl9jb21t
YW5kX3F1ZXVlKHNlbGYpOgogICAgICAgIHdoaWxlIFRydWU6CiAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgIGNvbW1hbmQsIF9wYXlsb2FkID0g
c2VsZi5jb21tYW5kX3F1ZXVlLmdldF9ub3dhaXQoKQogICAgICAgICAgICBleGNlcHQgcXVldWUuRW1wdHk6CiAgICAgICAgICAgICAgICBicmVhawoKICAg
ICAgICAgICAgaWYgY29tbWFuZCA9PSAidG9nZ2xlIjoKICAgICAgICAgICAgICAgIHNlbGYuX3RvZ2dsZV92aXNpYmlsaXR5KCkKICAgICAgICAgICAgZWxp
ZiBjb21tYW5kID09ICJvcGVuIjoKICAgICAgICAgICAgICAgIHNlbGYuX29wZW5fc2V0dGluZ3MoKQogICAgICAgICAgICBlbGlmIGNvbW1hbmQgPT0gInF1
aXQiOgogICAgICAgICAgICAgICAgc2VsZi5fcXVpdCgpCiAgICAgICAgICAgICAgICBicmVhawoKICAgIGRlZiBfdGljayhzZWxmKToKICAgICAgICBzZWxm
Ll9kcmFpbl9jb21tYW5kX3F1ZXVlKCkKICAgICAgICBzZWxmLl9kcmFpbl9jaGF0X3F1ZXVlKCkKCiAgICAgICAgbm93ID0gdGltZS5wZXJmX2NvdW50ZXIo
KQogICAgICAgIGR0ID0gY2xhbXAobm93IC0gc2VsZi5sYXN0X3RpY2ssIDAuMDAxLCAwLjA1KQogICAgICAgIHNlbGYubGFzdF90aWNrID0gbm93CgogICAg
ICAgIHBvaW50ZXJfeCwgcG9pbnRlcl95ID0gc2VsZi5fcG9pbnRlcl94eSgpCiAgICAgICAgc2VsZi5fdXBkYXRlX21vdGlvbihkdCwgcG9pbnRlcl94LCBw
b2ludGVyX3kpCiAgICAgICAgc2VsZi5fdXBkYXRlX2JsaW5rKG5vdykKCiAgICAgICAgaWYgc2VsZi52aXNpYmxlOgogICAgICAgICAgICBzZWxmLl9kcmF3
X3JvYm90KHBvaW50ZXJfeCwgcG9pbnRlcl95LCBkdCwgbm93KQogICAgICAgICAgICBzZWxmLl9yZXNpemVfd2luZG93KCkKCiAgICAgICAgc2VsZi5yb290
LmFmdGVyKDE2LCBzZWxmLl90aWNrKQoKCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6CiAgICBhcHAgPSBSb2JvdFBldEFwcCgpCiAgICBhcHAucnVuKCkN
Cg0KDQo=
__BYTE_SOURCE_END__
